<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BillingPlansSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('billing_plans')->upsert([
            [
                'slug'                     => 'trial',
                'name'                     => 'Trial',
                'name_uz'                  => 'Sinov',
                'description'              => 'Бесплатный пробный период для знакомства с системой',
                'price_monthly'            => 0,
                'price_yearly'             => 0,
                'price_uzs'                => 0,
                'activation_fee_uzs'       => 0,
                'earn_first_enabled'       => false,
                'earn_first_deduction_pct' => 0,
                'max_managers'             => 3,
                'max_cases'                => 50,
                'max_leads_per_month'      => 10,
                'has_marketplace'          => false,
                'has_priority_support'     => false,
                'has_api_access'           => false,
                'has_custom_domain'        => false,
                'has_white_label'          => false,
                'has_analytics'            => false,
                'trial_days'               => 45,
                'grace_period_days'        => 3,
                'stripe_price_id_monthly'  => null,
                'stripe_price_id_yearly'   => null,
                'features'                 => json_encode([
                    '45 дней бесплатно',
                    'До 3 менеджеров',
                    'До 50 активных заявок',
                    'SLA-дедлайны',
                    'Канбан-доска',
                    'Собственные клиенты и воронка продаж',
                ]),
                'sort_order'               => 0,
                'is_active'                => true,
                'is_public'                => true,
                'is_recommended'           => false,
                'created_at'               => now(),
                'updated_at'               => now(),
            ],
            [
                'slug'                     => 'starter',
                'name'                     => 'Starter',
                'name_uz'                  => 'Boshlang\'ich',
                'description'              => 'Для небольших агентств, начинающих автоматизацию',
                'price_monthly'            => 1900,
                'price_yearly'             => 18240,
                'price_uzs'                => 240000,
                'activation_fee_uzs'       => 50000,
                'earn_first_enabled'       => true,
                'earn_first_deduction_pct' => 15,
                'max_managers'             => 3,
                'max_cases'                => 50,
                'max_leads_per_month'      => 30,
                'has_marketplace'          => false,
                'has_priority_support'     => false,
                'has_api_access'           => false,
                'has_custom_domain'        => false,
                'has_white_label'          => false,
                'has_analytics'            => true,
                'trial_days'               => 0,
                'grace_period_days'        => 5,
                'stripe_price_id_monthly'  => null,
                'stripe_price_id_yearly'   => null,
                'features'                 => json_encode([
                    'До 3 менеджеров',
                    'До 50 активных заявок',
                    'SLA-дедлайны + уведомления',
                    'Канбан-доска',
                    'Telegram-уведомления клиентам',
                    'Скоринг-движок',
                    'Базовая аналитика',
                    'Собственные клиенты и воронка продаж',
                ]),
                'sort_order'               => 1,
                'is_active'                => true,
                'is_public'                => true,
                'is_recommended'           => false,
                'created_at'               => now(),
                'updated_at'               => now(),
            ],
            [
                'slug'                     => 'pro',
                'name'                     => 'Professional',
                'name_uz'                  => 'Professional',
                'description'              => 'Для растущих агентств с маркетплейсом и приоритетной поддержкой',
                'price_monthly'            => 4900,
                'price_yearly'             => 47040,
                'price_uzs'                => 620000,
                'activation_fee_uzs'       => 100000,
                'earn_first_enabled'       => true,
                'earn_first_deduction_pct' => 10,
                'max_managers'             => 10,
                'max_cases'                => 200,
                'max_leads_per_month'      => 100,
                'has_marketplace'          => true,
                'has_priority_support'     => false,
                'has_api_access'           => false,
                'has_custom_domain'        => false,
                'has_white_label'          => true,
                'has_analytics'            => true,
                'trial_days'               => 0,
                'grace_period_days'        => 7,
                'stripe_price_id_monthly'  => null,
                'stripe_price_id_yearly'   => null,
                'features'                 => json_encode([
                    'До 10 менеджеров',
                    'До 200 активных заявок',
                    'Листинг на маркетплейсе',
                    'Входящие лиды с маркетплейса',
                    'White-label Telegram-бот',
                    'Расширенная аналитика',
                    'Собственные клиенты + маркетплейс',
                    'Earn-first: удержание 10% с заказов',
                ]),
                'sort_order'               => 2,
                'is_active'                => true,
                'is_public'                => true,
                'is_recommended'           => true,
                'created_at'               => now(),
                'updated_at'               => now(),
            ],
            [
                'slug'                     => 'enterprise',
                'name'                     => 'Enterprise',
                'name_uz'                  => 'Korporativ',
                'description'              => 'Для крупных агентств с полным набором функций',
                'price_monthly'            => 9900,
                'price_yearly'             => 95040,
                'price_uzs'                => 1250000,
                'activation_fee_uzs'       => 200000,
                'earn_first_enabled'       => true,
                'earn_first_deduction_pct' => 7,
                'max_managers'             => 0,
                'max_cases'                => 0,
                'max_leads_per_month'      => 0,
                'has_marketplace'          => true,
                'has_priority_support'     => true,
                'has_api_access'           => true,
                'has_custom_domain'        => true,
                'has_white_label'          => true,
                'has_analytics'            => true,
                'trial_days'               => 0,
                'grace_period_days'        => 14,
                'stripe_price_id_monthly'  => null,
                'stripe_price_id_yearly'   => null,
                'features'                 => json_encode([
                    'Безлимитные менеджеры',
                    'Безлимитные заявки',
                    'Приоритетный значок на маркетплейсе',
                    'Персональный менеджер',
                    'Custom домен',
                    'API-доступ (Instagram, Facebook, сайт)',
                    'Лиды из соцсетей автоматом в CRM',
                    'SLA-гарантия 99.9%',
                    'Earn-first: удержание 7% с заказов',
                ]),
                'sort_order'               => 3,
                'is_active'                => true,
                'is_public'                => true,
                'is_recommended'           => false,
                'created_at'               => now(),
                'updated_at'               => now(),
            ],
        ], ['slug'], [
            'name', 'name_uz', 'description',
            'price_monthly', 'price_yearly', 'price_uzs',
            'activation_fee_uzs', 'earn_first_enabled', 'earn_first_deduction_pct',
            'max_managers', 'max_cases', 'max_leads_per_month',
            'has_marketplace', 'has_priority_support', 'has_api_access',
            'has_custom_domain', 'has_white_label', 'has_analytics',
            'trial_days', 'grace_period_days',
            'features', 'sort_order', 'is_public', 'is_recommended', 'updated_at',
        ]);
    }
}
