<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EmbassyDataSeeder extends Seeder
{
    public function run(): void
    {
        $embassies = [
            'DE' => [
                'embassy_name'        => 'Посольство Федеративной Республики Германия в Ташкенте',
                'embassy_address'     => 'ул. Шарафа Рашидова, 15',
                'embassy_city'        => 'Ташкент',
                'embassy_phone'       => '+998 71 120 84 40',
                'embassy_email'       => 'info@taschkent.diplo.de',
                'submission_type'     => 'visa_center',
                'visa_center_name'    => 'VFS Global (Германия)',
                'visa_center_address' => 'ул. Бухоро, 8А, Tashkent City Mall, 2 этаж',
                'visa_center_phone'   => '+998 78 140 08 30',
                'visa_center_website' => 'https://visa.vfsglobal.com/uzb/en/deu',
                'latitude'            => 41.3111200,
                'longitude'           => 69.2797100,
                'name_uz'             => 'Germaniya',
            ],
            'FR' => [
                'embassy_name'        => 'Посольство Французской Республики в Ташкенте',
                'embassy_address'     => 'ул. Истиклол, 25',
                'embassy_city'        => 'Ташкент',
                'embassy_phone'       => '+998 71 233 53 82',
                'embassy_email'       => 'visas.tachkent-amba@diplomatie.gouv.fr',
                'submission_type'     => 'visa_center',
                'visa_center_name'    => 'TLScontact (Франция)',
                'visa_center_address' => 'ул. Афросиаб, 12',
                'visa_center_phone'   => '+998 78 129 41 41',
                'visa_center_website' => 'https://fr.tlscontact.com/uz/TAS',
                'latitude'            => 41.3119800,
                'longitude'           => 69.2793400,
                'name_uz'             => 'Frantsiya',
            ],
            'IT' => [
                'embassy_name'        => 'Посольство Итальянской Республики в Ташкенте',
                'embassy_address'     => 'ул. Юсуфа Хос Хожиба, 40',
                'embassy_city'        => 'Ташкент',
                'embassy_phone'       => '+998 71 120 60 01',
                'embassy_email'       => 'ambasciata.tashkent@esteri.it',
                'submission_type'     => 'visa_center',
                'visa_center_name'    => 'VFS Global (Италия)',
                'visa_center_address' => 'ул. Бухоро, 8А, Tashkent City Mall, 2 этаж',
                'visa_center_phone'   => '+998 78 140 08 30',
                'visa_center_website' => 'https://visa.vfsglobal.com/uzb/en/ita',
                'latitude'            => 41.3145000,
                'longitude'           => 69.2635000,
                'name_uz'             => 'Italiya',
            ],
            'ES' => [
                'embassy_name'        => 'Посольство Королевства Испания в Ташкенте',
                'embassy_address'     => 'ул. Буюк Ипак Йули, 3А',
                'embassy_city'        => 'Ташкент',
                'embassy_phone'       => '+998 71 120 16 46',
                'embassy_email'       => 'emb.tashkent@maec.es',
                'submission_type'     => 'visa_center',
                'visa_center_name'    => 'BLS International (Испания)',
                'visa_center_address' => 'ул. Мустакиллик, 75Б',
                'visa_center_phone'   => '+998 78 150 03 80',
                'visa_center_website' => 'https://blsspain-uzbekistan.com',
                'latitude'            => 41.3125000,
                'longitude'           => 69.2550000,
                'name_uz'             => 'Ispaniya',
            ],
            'PL' => [
                'embassy_name'        => 'Посольство Республики Польша в Ташкенте',
                'embassy_address'     => 'ул. Чиланзар, кв. 10, дом 3',
                'embassy_city'        => 'Ташкент',
                'embassy_phone'       => '+998 71 120 86 48',
                'embassy_email'       => 'tashkent.amb.sekretariat@msz.gov.pl',
                'submission_type'     => 'visa_center',
                'visa_center_name'    => 'VFS Global (Польша)',
                'visa_center_address' => 'ул. Бухоро, 8А, Tashkent City Mall, 2 этаж',
                'visa_center_phone'   => '+998 78 140 08 30',
                'visa_center_website' => 'https://visa.vfsglobal.com/uzb/en/pol',
                'latitude'            => 41.2930000,
                'longitude'           => 69.2190000,
                'name_uz'             => 'Polsha',
            ],
            'CZ' => [
                'embassy_name'        => 'Посольство Чешской Республики в Ташкенте',
                'embassy_address'     => 'ул. Афросиаб, 3',
                'embassy_city'        => 'Ташкент',
                'embassy_phone'       => '+998 71 120 62 07',
                'embassy_email'       => 'tashkent@embassy.mzv.cz',
                'submission_type'     => 'embassy_direct',
                'visa_center_name'    => null,
                'visa_center_address' => null,
                'visa_center_phone'   => null,
                'visa_center_website' => null,
                'latitude'            => 41.3115000,
                'longitude'           => 69.2788000,
                'name_uz'             => 'Chexiya',
            ],
            'GB' => [
                'embassy_name'        => 'Посольство Великобритании в Ташкенте',
                'embassy_address'     => 'ул. Гулямова, 67',
                'embassy_city'        => 'Ташкент',
                'embassy_phone'       => '+998 71 120 15 00',
                'embassy_email'       => 'ukin.tashkent@fcdo.gov.uk',
                'submission_type'     => 'visa_center',
                'visa_center_name'    => 'TLScontact (Великобритания)',
                'visa_center_address' => 'ул. Амир Темур, 107Б, Business City',
                'visa_center_phone'   => '+998 78 129 41 00',
                'visa_center_website' => 'https://uk.tlscontact.com/uz/TAS',
                'latitude'            => 41.3140000,
                'longitude'           => 69.2720000,
                'name_uz'             => 'Buyuk Britaniya',
            ],
            'US' => [
                'embassy_name'        => 'Посольство Соединённых Штатов Америки в Ташкенте',
                'embassy_address'     => 'ул. Мойкурган, 3',
                'embassy_city'        => 'Ташкент',
                'embassy_phone'       => '+998 71 120 54 50',
                'embassy_email'       => 'tashkentconsular@state.gov',
                'submission_type'     => 'embassy_direct',
                'visa_center_name'    => null,
                'visa_center_address' => null,
                'visa_center_phone'   => null,
                'visa_center_website' => null,
                'latitude'            => 41.3377000,
                'longitude'           => 69.3387000,
                'name_uz'             => 'AQSh',
            ],
            'CA' => [
                'embassy_name'        => 'Посольство Канады (аккредитация из Анкары)',
                'embassy_address'     => 'Обращение через VAC',
                'embassy_city'        => 'Ташкент',
                'embassy_phone'       => null,
                'embassy_email'       => null,
                'submission_type'     => 'visa_center',
                'visa_center_name'    => 'VFS Global (Канада)',
                'visa_center_address' => 'ул. Бухоро, 8А, Tashkent City Mall, 2 этаж',
                'visa_center_phone'   => '+998 78 140 08 30',
                'visa_center_website' => 'https://visa.vfsglobal.com/uzb/en/can',
                'latitude'            => 41.3111200,
                'longitude'           => 69.2797100,
                'name_uz'             => 'Kanada',
            ],
            'KR' => [
                'embassy_name'        => 'Посольство Республики Корея в Ташкенте',
                'embassy_address'     => 'ул. Афросиаб, 7-7А',
                'embassy_city'        => 'Ташкент',
                'embassy_phone'       => '+998 71 252 31 51',
                'embassy_email'       => 'uzbek@mofa.go.kr',
                'submission_type'     => 'embassy_direct',
                'visa_center_name'    => null,
                'visa_center_address' => null,
                'visa_center_phone'   => null,
                'visa_center_website' => null,
                'latitude'            => 41.3108000,
                'longitude'           => 69.2815000,
                'name_uz'             => 'Janubiy Koreya',
            ],
            'AE' => [
                'embassy_name'        => 'Посольство Объединённых Арабских Эмиратов в Ташкенте',
                'embassy_address'     => 'ул. Бабура, 44',
                'embassy_city'        => 'Ташкент',
                'embassy_phone'       => '+998 71 140 11 31',
                'embassy_email'       => null,
                'submission_type'     => 'online',
                'visa_center_name'    => null,
                'visa_center_address' => null,
                'visa_center_phone'   => null,
                'visa_center_website' => null,
                'latitude'            => 41.3040000,
                'longitude'           => 69.2710000,
                'name_uz'             => 'BAA',
            ],
        ];

        foreach ($embassies as $code => $data) {
            DB::table('portal_countries')
                ->where('country_code', $code)
                ->update(array_merge($data, ['updated_at' => now()]));
        }

        $this->command->info('Embassy data seeded for ' . count($embassies) . ' countries.');
    }
}
