<?php

namespace Database\Seeders;

use App\Modules\LeadGen\Models\LeadChannel;
use Illuminate\Database\Seeder;

class LeadChannelSeeder extends Seeder
{
    public function run(): void
    {
        $channels = $this->channels();

        foreach ($channels as $data) {
            LeadChannel::updateOrCreate(
                ['code' => $data['code']],
                $data,
            );
        }
    }

    private function channels(): array
    {
        return [
            // ======================== МЕССЕНДЖЕРЫ ========================
            [
                'code' => 'telegram_bot',
                'name' => 'Telegram Bot',
                'name_uz' => 'Telegram Bot',
                'category' => 'messenger',
                'icon' => '🤖',
                'short_description' => 'Автоматический приём заявок через Telegram-бота. Клиент пишет боту, отвечает на вопросы — заявка создаётся в CRM.',
                'short_description_uz' => 'Telegram bot orqali avtomatik arizalarni qabul qilish. Mijoz botga yozadi, savollarga javob beradi — ariza CRM da yaratiladi.',
                'full_description' => "Telegram Bot — один из самых эффективных каналов для визовых агентств в Узбекистане. В стране более 20 миллионов пользователей Telegram, что делает его основным мессенджером.\n\nБот работает 24/7, принимает заявки даже ночью и в выходные. Клиент отправляет боту сообщение, отвечает на серию вопросов (страна, тип визы, сроки, количество человек) — и заявка автоматически создаётся в CRM.\n\nВы можете настроить приветственное сообщение, меню услуг, FAQ, рассылку статусов заявки. Бот может отправлять уведомления клиенту о смене статуса заявки.\n\nЭто дешёвый канал: создание бота бесплатно, поддержка минимальна. Подходит для агентств любого размера.",
                'full_description_uz' => "Telegram Bot — O'zbekistondagi viza agentliklari uchun eng samarali kanallardan biri. Mamlakatda 20 milliondan ortiq Telegram foydalanuvchisi bor.\n\nBot 24/7 ishlaydi, tunda ham, dam olish kunlarida ham arizalarni qabul qiladi. Mijoz botga xabar yuboradi, savollarga javob beradi — ariza avtomatik CRM da yaratiladi.\n\nSiz salomlashish xabarini, xizmatlar menyusini, FAQ ni sozlashingiz mumkin. Bot mijozga ariza holati o'zgarganligi haqida xabar yuborishi mumkin.",
                'how_it_works' => "1. Создаёте бота через @BotFather в Telegram\n2. Подключаете бота к VisaCRM через настройки\n3. Настраиваете сценарий опроса (страна, виза, контакт)\n4. Клиент пишет боту → отвечает на вопросы\n5. Заявка автоматически создаётся в CRM\n6. Менеджер получает уведомление и берёт в работу",
                'how_it_works_uz' => "1. Telegram da @BotFather orqali bot yarating\n2. Botni VisaCRM ga sozlamalarda ulang\n3. So'rov stsenariyasini sozlang\n4. Mijoz botga yozadi → savollarga javob beradi\n5. Ariza avtomatik CRM da yaratiladi\n6. Menejer xabar oladi va ishga oladi",
                'when_to_use' => 'Когда основная аудитория — пользователи Telegram. Подходит для Узбекистана и стран СНГ.',
                'when_not_to_use' => 'Если аудитория не использует Telegram (редко в УЗ). Если нужна сложная форма с загрузкой документов.',
                'use_cases' => 'Приём заявок на визу, рассылка статусов, FAQ по документам, запись на консультацию.',
                'effectiveness' => 'high',
                'effectiveness_factors' => 'Зависит от: продвижения бота, качества сценария, скорости ответа менеджера.',
                'complexity' => 'easy',
                'launch_speed' => '1_day',
                'requires_budget' => false,
                'requires_api' => 'partial',
                'enterprise_only' => false,
                'min_plan' => 'starter',
                'required_preparation' => 'Telegram-аккаунт, сценарий вопросов для бота, контент для FAQ.',
                'expected_result' => '5-20 заявок в месяц при минимальном продвижении, 50-100+ при активной рекламе бота.',
                'risks' => 'Бот может отпугнуть клиентов, если сценарий слишком длинный. Нужна быстрая реакция менеджера.',
                'best_practices' => "Делайте сценарий коротким (3-5 вопросов). Добавьте кнопку «Связаться с менеджером». Отвечайте в течение 5 минут.",
                'trends' => 'Telegram Mini Apps — следующий шаг эволюции ботов. Позволяют встроить полноценный UI прямо в мессенджер.',
                'recommended_for' => 'all',
                'cta_actions' => json_encode(['connect', 'instruction']),
                'sort_order' => 10,
                'is_active' => true,
                'coming_soon' => false,
            ],
            [
                'code' => 'telegram_webapp',
                'name' => 'Telegram Mini App',
                'name_uz' => 'Telegram Mini App',
                'category' => 'messenger',
                'icon' => '📱',
                'short_description' => 'Полноценное мини-приложение внутри Telegram с формой заявки, выбором страны и визы.',
                'short_description_uz' => 'Telegram ichida to\'liq mini-ilova: ariza formasi, davlat va viza tanlash.',
                'full_description' => "Telegram Mini App (WebApp) — это веб-страница, которая открывается прямо внутри Telegram. Клиент нажимает кнопку в боте и видит красивую форму с выбором страны, типа визы, датами.\n\nВ отличие от обычного бота, Mini App позволяет сделать визуальный интерфейс: выпадающие списки, календари, загрузку фото паспорта. Это значительно повышает конверсию.\n\nМини-приложение работает без установки, мгновенно загружается и выглядит как нативное приложение.",
                'full_description_uz' => "Telegram Mini App — Telegram ichida ochiluvchi veb-sahifa. Mijoz botda tugmani bosadi va chiroyli formani ko'radi: davlat, viza turi, sanalar.\n\nOddiy botdan farqi — vizual interfeys: tanlash ro'yxatlari, kalendarlar, passport suratini yuklash.",
                'how_it_works' => "1. Разрабатывается Mini App (веб-страница)\n2. Подключается к Telegram-боту\n3. Клиент нажимает кнопку в боте → открывается форма\n4. Заполняет данные → заявка уходит в CRM через API\n5. Менеджер получает новую заявку",
                'how_it_works_uz' => "1. Mini App (veb-sahifa) ishlab chiqiladi\n2. Telegram botga ulanadi\n3. Mijoz tugmani bosadi → forma ochiladi\n4. Ma'lumotlarni to'ldiradi → ariza API orqali CRM ga ketadi",
                'when_to_use' => 'Когда нужна красивая форма заявки с визуальным UI прямо в Telegram.',
                'when_not_to_use' => 'Если достаточно простого бота с текстовыми вопросами.',
                'use_cases' => 'Форма заявки на визу, калькулятор стоимости, запись на консультацию.',
                'effectiveness' => 'high',
                'effectiveness_factors' => 'Зависит от дизайна формы, удобства, продвижения бота.',
                'complexity' => 'medium',
                'launch_speed' => '1_week',
                'requires_budget' => false,
                'requires_api' => 'yes',
                'enterprise_only' => false,
                'min_plan' => 'pro',
                'required_preparation' => 'Telegram-бот, дизайн формы, API для приёма заявок.',
                'expected_result' => 'Конверсия на 30-50% выше чем у обычного бота.',
                'risks' => 'Требует разработки. Может медленно загружаться при плохом интернете.',
                'best_practices' => 'Минимум полей в форме. Автозаполнение из Telegram-профиля. Мгновенная обратная связь.',
                'trends' => 'Telegram активно развивает Mini Apps. Это будущее Telegram-ботов.',
                'recommended_for' => 'medium',
                'cta_actions' => json_encode(['connect', 'instruction']),
                'sort_order' => 20,
                'is_active' => true,
                'coming_soon' => true,
            ],
            [
                'code' => 'whatsapp_business',
                'name' => 'WhatsApp Business',
                'name_uz' => 'WhatsApp Business',
                'category' => 'messenger',
                'icon' => '💬',
                'short_description' => 'Приём заявок через WhatsApp Business с шаблонами ответов и каталогом услуг.',
                'short_description_uz' => 'WhatsApp Business orqali javob shablonlari va xizmatlar katalogi bilan arizalar qabul qilish.',
                'full_description' => "WhatsApp Business — бесплатный бизнес-аккаунт для общения с клиентами. Позволяет создать профиль агентства, каталог услуг, быстрые ответы.\n\nВ Узбекистане WhatsApp используется реже Telegram, но популярен среди старшей аудитории и международных клиентов. Если агентство работает с иностранными клиентами — WhatsApp обязателен.\n\nМожно настроить автоответы, приветственные сообщения, шаблоны для типовых вопросов.",
                'full_description_uz' => "WhatsApp Business — mijozlar bilan muloqot uchun bepul biznes-hisob. Agentlik profilini, xizmatlar katalogini, tezkor javoblarni yaratish imkonini beradi.\n\nO'zbekistonda WhatsApp Telegramga qaraganda kam ishlatiladi, lekin katta yoshdagi auditoriya va xalqaro mijozlar orasida mashhur.",
                'how_it_works' => "1. Скачиваете WhatsApp Business\n2. Создаёте бизнес-профиль агентства\n3. Настраиваете каталог услуг и автоответы\n4. Публикуете ссылку wa.me/номер\n5. Клиент пишет → менеджер обрабатывает → создаёт заявку в CRM",
                'how_it_works_uz' => "1. WhatsApp Business yuklab oling\n2. Agentlik biznes-profilini yarating\n3. Xizmatlar katalogi va avtomatik javoblarni sozlang\n4. wa.me/raqam havolasini joylashtiring\n5. Mijoz yozadi → menejer ariza yaratadi",
                'when_to_use' => 'Когда работаете с международными клиентами или старшей аудиторией.',
                'when_not_to_use' => 'Если вся аудитория в Telegram и нет международных клиентов.',
                'use_cases' => 'Консультации, приём заявок от иностранных клиентов, рассылка статусов.',
                'effectiveness' => 'medium',
                'effectiveness_factors' => 'Зависит от аудитории. Высокая для международных клиентов.',
                'complexity' => 'easy',
                'launch_speed' => '1_day',
                'requires_budget' => false,
                'requires_api' => 'no',
                'enterprise_only' => false,
                'min_plan' => 'starter',
                'required_preparation' => 'Номер телефона для WhatsApp, фото и описание агентства.',
                'expected_result' => '3-15 обращений в месяц, зависит от продвижения номера.',
                'risks' => 'Ручная обработка сообщений. Нет автоматического создания заявок в CRM.',
                'best_practices' => 'Отвечайте в течение 5 минут. Используйте шаблоны. Добавьте каталог с ценами.',
                'trends' => 'WhatsApp Business API позволяет автоматизировать через чат-ботов.',
                'recommended_for' => 'all',
                'cta_actions' => json_encode(['connect', 'instruction']),
                'sort_order' => 30,
                'is_active' => true,
                'coming_soon' => false,
            ],
            [
                'code' => 'instagram_direct',
                'name' => 'Instagram Direct',
                'name_uz' => 'Instagram Direct',
                'category' => 'messenger',
                'icon' => '📸',
                'short_description' => 'Приём заявок через Instagram Direct. Клиенты пишут в личные сообщения после просмотра контента.',
                'short_description_uz' => 'Instagram Direct orqali arizalar qabul qilish. Mijozlar kontentni ko\'rganidan keyin shaxsiy xabarlarga yozadi.',
                'full_description' => "Instagram — один из ключевых каналов для визовых агентств. Визуальный контент (фото виз, историй успеха, инфографика) привлекает аудиторию, а Direct — основной канал коммуникации.\n\nПубликуйте полезный контент: чек-листы документов, сроки, стоимость виз по странам. Аудитория пишет в Direct → менеджер консультирует и создаёт заявку.\n\nInstagram особенно эффективен для Шенгенских виз, учебных виз и иммиграционных программ.",
                'full_description_uz' => "Instagram — viza agentliklari uchun asosiy kanallardan biri. Vizual kontent auditoriyani jalb qiladi, Direct esa asosiy muloqot kanali.\n\nFoydali kontent joylashtiring: hujjatlar chek-listlari, muddatlar, viza narxlari. Auditoriya Directga yozadi → menejer maslahat beradi va ariza yaratadi.",
                'how_it_works' => "1. Создаёте бизнес-аккаунт Instagram\n2. Публикуете контент о визах и странах\n3. Клиент видит пост → пишет в Direct\n4. Менеджер консультирует и создаёт заявку в CRM\n5. Можно настроить автоответы через Meta Business Suite",
                'how_it_works_uz' => "1. Instagram biznes-hisob yarating\n2. Vizalar va davlatlar haqida kontent joylashtiring\n3. Mijoz postni ko'radi → Directga yozadi\n4. Menejer maslahat beradi va CRM da ariza yaratadi",
                'when_to_use' => 'Когда есть ресурсы на создание визуального контента. Отлично для B2C.',
                'when_not_to_use' => 'Если нет времени на регулярный контент (минимум 3-5 постов в неделю).',
                'use_cases' => 'Продвижение визовых услуг, образовательный контент, сбор лидов через stories.',
                'effectiveness' => 'high',
                'effectiveness_factors' => 'Зависит от: качества контента, регулярности, скорости ответа в Direct.',
                'complexity' => 'medium',
                'launch_speed' => '3_days',
                'requires_budget' => false,
                'requires_api' => 'no',
                'enterprise_only' => false,
                'min_plan' => 'starter',
                'required_preparation' => 'Бизнес-аккаунт Instagram, контент-план, фото/видео материалы.',
                'expected_result' => '10-50 обращений в месяц при регулярном контенте.',
                'risks' => 'Требует постоянного контента. Алгоритмы Instagram могут снизить охваты.',
                'best_practices' => 'Reels работают лучше постов. Stories с опросами вовлекают. Отвечайте в Direct до 1 часа.',
                'trends' => 'Instagram Reels — главный формат 2025-2026. Короткие видео о визах набирают миллионы просмотров.',
                'recommended_for' => 'all',
                'cta_actions' => json_encode(['instruction']),
                'sort_order' => 40,
                'is_active' => true,
                'coming_soon' => false,
            ],
            // ======================== РЕКЛАМА ========================
            [
                'code' => 'google_ads_search',
                'name' => 'Google Ads (Поиск)',
                'name_uz' => 'Google Ads (Qidiruv)',
                'category' => 'advertising',
                'icon' => '🔍',
                'short_description' => 'Реклама в поиске Google. Клиент ищет «виза в Италию» → видит вашу рекламу → оставляет заявку.',
                'short_description_uz' => 'Google qidiruvida reklama. Mijoz «Italiyaga viza» deb qidiradi → sizning reklamangizni ko\'radi → ariza qoldiradi.',
                'full_description' => "Google Ads Search — самый целевой рекламный канал. Клиент уже ищет визовые услуги — вы показываете ему рекламу именно в момент потребности.\n\nДля визовых агентств ключевые запросы: «виза в [страну]», «шенген виза Ташкент», «оформление визы Узбекистан». CPC в Узбекистане относительно низкий ($0.3-1.5).\n\nОбъявление ведёт на лендинг или форму заявки. Клиент заполняет → заявка в CRM.",
                'full_description_uz' => "Google Ads Search — eng maqsadli reklama kanali. Mijoz allaqachon viza xizmatlarini qidirmoqda — siz unga ehtiyoj paytida reklama ko'rsatasiz.\n\nAsosiy so'rovlar: «viza [davlat]ga», «shengen viza Toshkent». O'zbekistonda CPC nisbatan past ($0.3-1.5).",
                'how_it_works' => "1. Создаёте аккаунт Google Ads\n2. Подбираете ключевые слова (виза + страна)\n3. Пишете объявления\n4. Настраиваете бюджет и геотаргетинг\n5. Клиент ищет → видит рекламу → переходит на сайт\n6. Заполняет форму → заявка в CRM",
                'how_it_works_uz' => "1. Google Ads hisobi yarating\n2. Kalit so'zlarni tanlang (viza + davlat)\n3. E'lonlar yozing\n4. Byudjet va geotargetingni sozlang\n5. Mijoz qidiradi → reklamani ko'radi → saytga o'tadi\n6. Formani to'ldiradi → ariza CRM ga",
                'when_to_use' => 'Когда нужны клиенты с конкретным запросом «хочу визу». Самая высокая конверсия.',
                'when_not_to_use' => 'Если бюджет менее $300/мес. Если нет сайта/лендинга для приёма трафика.',
                'use_cases' => 'Продвижение визовых услуг по конкретным странам, сезонные кампании.',
                'effectiveness' => 'very_high',
                'effectiveness_factors' => 'Зависит от: бюджета, качества объявлений, посадочной страницы, скорости обработки.',
                'complexity' => 'medium',
                'launch_speed' => '3_days',
                'requires_budget' => true,
                'requires_api' => 'no',
                'enterprise_only' => false,
                'min_plan' => 'pro',
                'required_preparation' => 'Сайт/лендинг, Google Ads аккаунт, бюджет от $300/мес, список ключевых слов.',
                'expected_result' => '20-100 заявок в месяц при бюджете $500-2000.',
                'risks' => 'Конкуренция повышает CPC. Нецелевые клики расходуют бюджет. Нужна оптимизация.',
                'best_practices' => 'Используйте минус-слова. Создайте отдельные кампании по странам. A/B тестируйте объявления.',
                'trends' => 'Performance Max кампании Google автоматизируют размещение. AI-генерация объявлений.',
                'recommended_for' => 'medium',
                'cta_actions' => json_encode(['instruction', 'learn_more']),
                'sort_order' => 70,
                'is_active' => true,
                'coming_soon' => false,
            ],
            [
                'code' => 'meta_ads',
                'name' => 'Meta Ads (Instagram/Facebook)',
                'name_uz' => 'Meta Ads (Instagram/Facebook)',
                'category' => 'advertising',
                'icon' => '📣',
                'short_description' => 'Таргетированная реклама в Instagram и Facebook. Показ рекламы целевой аудитории по интересам.',
                'short_description_uz' => 'Instagram va Facebook da maqsadli reklama. Qiziqishlar bo\'yicha maqsadli auditoriyaga reklama ko\'rsatish.',
                'full_description' => "Meta Ads — мощная рекламная платформа для визовых агентств. Позволяет точно таргетировать аудиторию: интересы (путешествия, визы, эмиграция), география, возраст, поведение.\n\nОсобенно эффективны Lead Ads — формы заявки прямо внутри Instagram/Facebook. Клиент нажимает кнопку → заполняет форму не покидая приложения → заявка уходит вам.\n\nДля визовых агентств лучше всего работают: Reels реклама, Stories реклама, Lead Forms.",
                'full_description_uz' => "Meta Ads — viza agentliklari uchun kuchli reklama platformasi. Auditoriyani aniq maqsadlash imkonini beradi: qiziqishlar, geografiya, yosh.\n\nLead Ads ayniqsa samarali — ariza formasi Instagram/Facebook ichida. Mijoz tugmani bosadi → ilovadan chiqmay formani to'ldiradi.",
                'how_it_works' => "1. Создаёте Meta Business аккаунт\n2. Настраиваете аудиторию (гео, интересы, возраст)\n3. Создаёте креативы (фото/видео)\n4. Запускаете кампанию с Lead Form или трафиком на сайт\n5. Клиент видит рекламу → заполняет форму\n6. Заявка приходит в CRM (через API на Enterprise)",
                'how_it_works_uz' => "1. Meta Business hisob yarating\n2. Auditoriyani sozlang (geo, qiziqishlar, yosh)\n3. Kreativlar yarating (foto/video)\n4. Lead Form yoki saytga trafik bilan kampaniya boshlang",
                'when_to_use' => 'Когда нужен большой охват. Для продвижения конкретных направлений (Шенген, Корея, Канада).',
                'when_not_to_use' => 'Если бюджет менее $200/мес. Если нет качественных визуальных материалов.',
                'use_cases' => 'Продвижение визовых услуг, сезонные акции, ретаргетинг посетителей сайта.',
                'effectiveness' => 'high',
                'effectiveness_factors' => 'Зависит от: качества креативов, таргетинга, бюджета, обработки лидов.',
                'complexity' => 'medium',
                'launch_speed' => '3_days',
                'requires_budget' => true,
                'requires_api' => 'partial',
                'enterprise_only' => false,
                'min_plan' => 'pro',
                'required_preparation' => 'Meta Business аккаунт, креативы, бюджет от $200/мес.',
                'expected_result' => '15-80 заявок в месяц при бюджете $300-1500.',
                'risks' => 'Модерация Meta может отклонить объявления. Конкуренция растёт.',
                'best_practices' => 'Используйте Lead Forms. Тестируйте разные креативы. Ретаргетинг повышает конверсию в 2-3 раза.',
                'trends' => 'Advantage+ кампании Meta с AI-оптимизацией. Reels реклама набирает обороты.',
                'recommended_for' => 'medium',
                'cta_actions' => json_encode(['instruction', 'learn_more']),
                'sort_order' => 80,
                'is_active' => true,
                'coming_soon' => false,
            ],
            // ======================== ВЕБ ========================
            [
                'code' => 'own_website',
                'name' => 'Собственный сайт',
                'name_uz' => 'O\'z veb-sayt',
                'category' => 'web',
                'icon' => '🌐',
                'short_description' => 'Сайт агентства с формой заявки, описанием услуг и контактами. Основа онлайн-присутствия.',
                'short_description_uz' => 'Agentlik sayti: ariza formasi, xizmatlar tavsifi va kontaktlar. Onlayn mavjudlikning asosi.',
                'full_description' => "Собственный сайт — фундамент всех digital-каналов. Это куда ведёт реклама, куда попадает клиент из поиска, куда указывают все ваши контакты.\n\nСайт визового агентства должен содержать: каталог стран и виз, калькулятор стоимости, форму заявки, отзывы клиентов, контакты и адрес.\n\nВажно: сайт без трафика бесполезен. Нужно продвигать через SEO, рекламу или соцсети.",
                'full_description_uz' => "O'z veb-sayt — barcha digital kanallarning asosi. Reklama shu yerga olib keladi, mijoz qidiruvdan shu yerga tushadi.\n\nViza agentligi sayti o'z ichiga olishi kerak: davlatlar va vizalar katalogi, narx kalkulyatori, ariza formasi, mijozlar fikrlari.",
                'how_it_works' => "1. Создаёте сайт (конструктор или заказ у разработчика)\n2. Размещаете каталог услуг, страны, цены\n3. Добавляете форму заявки\n4. Подключаете форму к CRM (через виджет или API)\n5. Продвигаете сайт через SEO и рекламу\n6. Клиент находит сайт → заполняет форму → заявка в CRM",
                'how_it_works_uz' => "1. Sayt yarating (konstruktor yoki dasturchi)\n2. Xizmatlar katalogi, davlatlar, narxlarni joylashtiring\n3. Ariza formasi qo'shing\n4. Formani CRM ga ulang\n5. SEO va reklama orqali saytni targ'ib qiling",
                'when_to_use' => 'Всегда. Сайт — обязательный элемент присутствия в интернете.',
                'when_not_to_use' => 'Никогда. Сайт нужен всем. Но не тратьте на него весь бюджет без плана продвижения.',
                'use_cases' => 'Основная посадочная страница, SEO-продвижение, приём заявок.',
                'effectiveness' => 'high',
                'effectiveness_factors' => 'Зависит от: SEO, рекламы, качества контента, скорости загрузки.',
                'complexity' => 'medium',
                'launch_speed' => '2_weeks',
                'requires_budget' => true,
                'requires_api' => 'no',
                'enterprise_only' => false,
                'min_plan' => 'starter',
                'required_preparation' => 'Домен, хостинг, контент (тексты, фото), структура сайта.',
                'expected_result' => 'От 5 до 200+ заявок/мес в зависимости от продвижения.',
                'risks' => 'Без продвижения сайт не приносит трафик. Устаревший дизайн отпугивает клиентов.',
                'best_practices' => 'Мобильная адаптация обязательна. Скорость загрузки < 3 сек. Форма заявки на каждой странице.',
                'trends' => 'AI-чатботы на сайте. Персонализация контента. PWA.',
                'recommended_for' => 'all',
                'cta_actions' => json_encode(['instruction']),
                'sort_order' => 120,
                'is_active' => true,
                'coming_soon' => false,
            ],
            [
                'code' => 'crm_form',
                'name' => 'Встроенная форма VisaCRM',
                'name_uz' => 'VisaCRM ichki formasi',
                'category' => 'web',
                'icon' => '📋',
                'short_description' => 'Готовая форма заявки от VisaCRM. Клиент заполняет — заявка автоматически в CRM.',
                'short_description_uz' => 'VisaCRM ning tayyor ariza formasi. Mijoz to\'ldiradi — ariza avtomatik CRM ga tushadi.',
                'full_description' => "Встроенная форма VisaCRM — самый быстрый способ начать принимать заявки онлайн. Форма уже готова, данные сразу попадают в CRM.\n\nВы получаете уникальную ссылку на форму заявки, которую можно разместить в соцсетях, Telegram, на визитках. Клиент заполняет → заявка создаётся в CRM → менеджер получает уведомление.\n\nНикакой разработки, никаких интеграций — работает из коробки.",
                'full_description_uz' => "VisaCRM ichki formasi — onlayn arizalarni qabul qilishning eng tez usuli. Forma tayyor, ma'lumotlar darhol CRM ga tushadi.\n\nSiz ariza formasi uchun noyob havola olasiz. Uni ijtimoiy tarmoqlarda, Telegramda, tashrifnomalarda joylashtirishingiz mumkin.",
                'how_it_works' => "1. Активируете форму в настройках VisaCRM\n2. Получаете уникальную ссылку\n3. Размещаете ссылку везде: Telegram, Instagram, визитки\n4. Клиент переходит → заполняет → заявка в CRM\n5. Менеджер получает уведомление",
                'how_it_works_uz' => "1. VisaCRM sozlamalarida formani faollashtiring\n2. Noyob havolani oling\n3. Havolani hamma joyga joylashtiring\n4. Mijoz o'tadi → to'ldiradi → ariza CRM ga\n5. Menejer xabar oladi",
                'when_to_use' => 'Когда нужно быстро начать принимать заявки без разработки.',
                'when_not_to_use' => 'Если нужен полностью кастомный дизайн формы.',
                'use_cases' => 'Быстрый старт, ссылка в соцсетях, QR на визитке.',
                'effectiveness' => 'medium',
                'effectiveness_factors' => 'Зависит от продвижения ссылки. Сама форма — только инструмент приёма.',
                'complexity' => 'easy',
                'launch_speed' => '1_day',
                'requires_budget' => false,
                'requires_api' => 'no',
                'enterprise_only' => false,
                'min_plan' => 'pro',
                'required_preparation' => 'Ничего. Форма готова в VisaCRM.',
                'expected_result' => 'Зависит от продвижения ссылки. Канал приёма, а не генерации.',
                'risks' => 'Минимальные. Форма работает из коробки.',
                'best_practices' => 'Размещайте ссылку везде. Добавьте QR-код на визитки. Закрепите в Telegram-канале.',
                'trends' => 'Формы с предзаполнением данных. Multi-step формы повышают конверсию.',
                'recommended_for' => 'all',
                'cta_actions' => json_encode(['connect']),
                'sort_order' => 140,
                'is_active' => true,
                'coming_soon' => false,
            ],
            [
                'code' => 'website_widget',
                'name' => 'Виджет заявки на сайт',
                'name_uz' => 'Sayt uchun ariza vidjeti',
                'category' => 'web',
                'icon' => '🧩',
                'short_description' => 'JavaScript-виджет для встраивания формы заявки VisaCRM на любой сайт.',
                'short_description_uz' => 'VisaCRM ariza formasini istalgan saytga joylashtirish uchun JavaScript-vidjet.',
                'full_description' => "Виджет VisaCRM — готовый JavaScript-код, который встраивается на любой сайт. Выглядит как кнопка или плавающая форма. Клиент нажимает → открывается форма → данные отправляются в CRM.\n\nЭто мост между вашим сайтом и CRM: не нужно разрабатывать форму, настраивать интеграцию, писать код обработки.",
                'full_description_uz' => "VisaCRM vidjeti — istalgan saytga joylashtiriladigan tayyor JavaScript-kod. Tugma yoki suzuvchi forma ko'rinishida. Mijoz bosadi → forma ochiladi → ma'lumotlar CRM ga yuboriladi.",
                'how_it_works' => "1. Копируете код виджета из настроек VisaCRM\n2. Вставляете на свой сайт (1 строка HTML)\n3. На сайте появляется кнопка/форма\n4. Клиент заполняет → заявка в CRM\n5. Менеджер обрабатывает",
                'how_it_works_uz' => "1. VisaCRM sozlamalaridan vidjet kodini nusxalang\n2. O'z saytingizga joylashtiring (1 qator HTML)\n3. Saytda tugma/forma paydo bo'ladi\n4. Mijoz to'ldiradi → ariza CRM ga",
                'when_to_use' => 'Когда есть свой сайт и нужна быстрая интеграция формы заявки.',
                'when_not_to_use' => 'Если нет сайта. Если нужна глубокая кастомизация формы.',
                'use_cases' => 'Встраивание формы заявки на существующий сайт агентства.',
                'effectiveness' => 'medium',
                'effectiveness_factors' => 'Зависит от трафика сайта и расположения виджета.',
                'complexity' => 'easy',
                'launch_speed' => '1_day',
                'requires_budget' => false,
                'requires_api' => 'no',
                'enterprise_only' => false,
                'min_plan' => 'pro',
                'required_preparation' => 'Сайт с доступом к HTML-коду.',
                'expected_result' => 'Конверсия сайта растёт на 15-30% за счёт удобной формы.',
                'risks' => 'Минимальные. Не влияет на скорость загрузки сайта.',
                'best_practices' => 'Размещайте на всех страницах сайта. Плавающая кнопка в правом нижнем углу.',
                'trends' => 'Виджеты с AI-чатботом. Мультишаговые формы.',
                'recommended_for' => 'all',
                'cta_actions' => json_encode(['connect', 'instruction']),
                'sort_order' => 150,
                'is_active' => true,
                'coming_soon' => true,
            ],
            // ======================== SEO/КОНТЕНТ ========================
            [
                'code' => 'seo_pages',
                'name' => 'SEO-страницы по странам',
                'name_uz' => 'Davlatlar bo\'yicha SEO-sahifalar',
                'category' => 'content_seo',
                'icon' => '📄',
                'short_description' => 'Оптимизированные страницы «виза в [страну]» для привлечения бесплатного трафика из Google.',
                'short_description_uz' => 'Google dan bepul trafik jalb qilish uchun «[davlat]ga viza» optimallashtirilgan sahifalar.',
                'full_description' => "SEO-страницы — долгосрочная инвестиция в бесплатный трафик. Вы создаёте страницу «Виза в Италию из Узбекистана», оптимизируете её под поисковые запросы — и Google начинает показывать её в результатах.\n\nДля визового агентства это золотая жила: люди ищут «виза в Корею стоимость», «документы на шенген Ташкент», «виза в Канаду 2026» — и находят ваш сайт.\n\nТребуется время (3-6 месяцев), но результат — стабильный поток клиентов без расходов на рекламу.",
                'full_description_uz' => "SEO-sahifalar — bepul trafikka uzoq muddatli investitsiya. Siz «O'zbekistondan Italiyaga viza» sahifasini yaratasiz, qidiruv so'rovlari uchun optimallashtirasiz — va Google natijalarida ko'rsata boshlaydi.\n\nVaqt talab etiladi (3-6 oy), lekin natija — reklama xarajatlarisiz barqaror mijozlar oqimi.",
                'how_it_works' => "1. Определяете популярные страны и запросы\n2. Создаёте страницы: виза в [страну], стоимость, документы\n3. Оптимизируете: title, description, заголовки, текст\n4. Публикуете и ждёте индексации (1-3 мес)\n5. Google начинает показывать ваши страницы\n6. Клиент находит → читает → оставляет заявку",
                'how_it_works_uz' => "1. Mashhur davlatlar va so'rovlarni aniqlang\n2. Sahifalar yarating: [davlat]ga viza, narx, hujjatlar\n3. Optimallashtiring: title, description, sarlavhalar\n4. Nashr qiling va indeksatsiyani kuting (1-3 oy)",
                'when_to_use' => 'Всегда. SEO — основа долгосрочного бесплатного трафика.',
                'when_not_to_use' => 'Если нужны заявки уже сегодня (SEO работает через 3-6 месяцев).',
                'use_cases' => 'Привлечение органического трафика, экспертное позиционирование.',
                'effectiveness' => 'very_high',
                'effectiveness_factors' => 'Зависит от: качества контента, конкуренции по запросам, авторитета домена.',
                'complexity' => 'medium',
                'launch_speed' => '2_weeks',
                'requires_budget' => false,
                'requires_api' => 'no',
                'enterprise_only' => false,
                'min_plan' => 'starter',
                'required_preparation' => 'Сайт, список стран и виз, тексты для каждой страницы.',
                'expected_result' => 'Через 6 мес: 100-500+ посетителей/мес бесплатно. 10-50 заявок/мес.',
                'risks' => 'Долгий срок окупаемости. Алгоритмы Google могут измениться. Конкуренция.',
                'best_practices' => 'Одна страница = одна страна. Уникальный контент. Регулярное обновление цен и требований.',
                'trends' => 'AI-генерация контента ускоряет создание страниц. Google ценит экспертный контент.',
                'recommended_for' => 'all',
                'cta_actions' => json_encode(['instruction']),
                'sort_order' => 180,
                'is_active' => true,
                'coming_soon' => false,
            ],
            // ======================== ПАРТНЁРСТВО ========================
            [
                'code' => 'referral',
                'name' => 'Реферальная программа',
                'name_uz' => 'Referal dasturi',
                'category' => 'partnership',
                'icon' => '🤝',
                'short_description' => 'Клиенты рекомендуют вас друзьям и получают бонус. Сарафанное радио с мотивацией.',
                'short_description_uz' => 'Mijozlar sizni do\'stlariga tavsiya qiladi va bonus oladi. Motivatsiyali og\'zaki reklama.',
                'full_description' => "Реферальная программа — один из самых конверсионных каналов. Рекомендация от знакомого вызывает доверие в 10 раз больше, чем реклама.\n\nКлиент получает визу → доволен → рекомендует другу → друг оформляет визу → клиент получает бонус (скидка на следующую визу, кэшбэк).\n\nДля визовых агентств это особенно актуально: виза — это стресс, и люди доверяют рекомендациям.",
                'full_description_uz' => "Referal dasturi — eng konversion kanallardan biri. Tanishdan tavsiya reklamadan 10 baravar ko'proq ishonch hosil qiladi.\n\nMijoz viza oladi → mamnun → do'stiga tavsiya qiladi → do'st viza rasmiylashtiryapti → mijoz bonus oladi.",
                'how_it_works' => "1. Создаёте условия программы (бонус за рекомендацию)\n2. Информируете клиентов после успешного оформления визы\n3. Клиент делится ссылкой/кодом с друзьями\n4. Друг оставляет заявку → указывает реферальный код\n5. После оформления визы → оба получают бонус",
                'how_it_works_uz' => "1. Dastur shartlarini yarating (tavsiya uchun bonus)\n2. Viza muvaffaqiyatli rasmiylashtirilgandan keyin mijozlarni xabardor qiling\n3. Mijoz do'stlari bilan havola/kodni ulashadi\n4. Do'st ariza qoldiradi → referal kodni ko'rsatadi",
                'when_to_use' => 'Когда есть довольные клиенты (а они должны быть!). После каждой успешной визы.',
                'when_not_to_use' => 'Если качество услуг низкое — негативные отзывы опаснее.',
                'use_cases' => 'Привлечение клиентов через сарафанное радио с мотивацией.',
                'effectiveness' => 'high',
                'effectiveness_factors' => 'Зависит от: качества услуг, размера бонуса, удобства рекомендации.',
                'complexity' => 'easy',
                'launch_speed' => '3_days',
                'requires_budget' => false,
                'requires_api' => 'no',
                'enterprise_only' => false,
                'min_plan' => 'starter',
                'required_preparation' => 'Условия программы, система учёта рефералов.',
                'expected_result' => '10-30% новых клиентов через рекомендации при хорошем сервисе.',
                'risks' => 'Минимальные. Бонус выплачивается только после оформления визы.',
                'best_practices' => 'Бонус обоим (и рекомендателю, и новому клиенту). Простая механика. Напоминайте при выдаче визы.',
                'trends' => 'Цифровые реферальные программы с автотрекингом. Интеграция с CRM.',
                'recommended_for' => 'all',
                'cta_actions' => json_encode(['connect', 'instruction']),
                'sort_order' => 220,
                'is_active' => true,
                'coming_soon' => false,
            ],
            [
                'code' => 'partners',
                'name' => 'Партнёры и турагенты',
                'name_uz' => 'Hamkorlar va turagentlar',
                'category' => 'partnership',
                'icon' => '🏢',
                'short_description' => 'Сотрудничество с турагентствами, образовательными центрами и бизнес-организациями.',
                'short_description_uz' => 'Turagentliklar, ta\'lim markazlari va biznes tashkilotlari bilan hamkorlik.',
                'full_description' => "Партнёрские каналы — это B2B-сотрудничество с организациями, у которых уже есть ваша целевая аудитория.\n\nТурагентства отправляют клиентов на визу перед туром. Образовательные центры — студентов на учебные визы. Бизнес-организации — сотрудников на деловые визы.\n\nВы платите комиссию партнёру за каждого клиента (10-20%) или работаете по бартеру.",
                'full_description_uz' => "Hamkorlik kanallari — allaqachon maqsadli auditoriyasi bo'lgan tashkilotlar bilan B2B hamkorlik.\n\nTuragentliklar turdan oldin mijozlarni vizaga yuboradi. Ta'lim markazlari — talabalarni o'qish vizasiga. Biznes tashkilotlari — xodimlarni ish vizasiga.",
                'how_it_works' => "1. Определяете потенциальных партнёров (турагентства, вузы, бизнес-центры)\n2. Предлагаете условия сотрудничества (комиссия, бартер)\n3. Подписываете соглашение\n4. Партнёр направляет клиентов → вы обрабатываете\n5. Выплачиваете комиссию за каждого клиента",
                'how_it_works_uz' => "1. Potensial hamkorlarni aniqlang (turagentliklar, universitetlar)\n2. Hamkorlik shartlarini taklif qiling (komissiya, barter)\n3. Shartnoma imzolang\n4. Hamkor mijozlarni yo'naltiradi → siz ishlaysiz",
                'when_to_use' => 'Когда хотите стабильный поток B2B-клиентов. Особенно для учебных и деловых виз.',
                'when_not_to_use' => 'Если не готовы делить маржу с партнёрами.',
                'use_cases' => 'Учебные визы через вузы, туристические через турагентства, деловые через бизнес-центры.',
                'effectiveness' => 'high',
                'effectiveness_factors' => 'Зависит от: количества партнёров, качества отношений, размера комиссии.',
                'complexity' => 'medium',
                'launch_speed' => '1_week',
                'requires_budget' => false,
                'requires_api' => 'no',
                'enterprise_only' => false,
                'min_plan' => 'starter',
                'required_preparation' => 'Предложение для партнёров, шаблон соглашения, система учёта.',
                'expected_result' => '5-30 клиентов/мес от каждого активного партнёра.',
                'risks' => 'Партнёр может переключиться на конкурента. Нужен постоянный контакт.',
                'best_practices' => 'Платите комиссию быстро. Давайте партнёру статус заявки. Обучайте партнёров вашим услугам.',
                'trends' => 'Цифровые партнёрские платформы. Автоматический учёт лидов от партнёров.',
                'recommended_for' => 'all',
                'cta_actions' => json_encode(['instruction']),
                'sort_order' => 230,
                'is_active' => true,
                'coming_soon' => false,
            ],
            // ======================== API / АВТОМАТИЗАЦИЯ ========================
            [
                'code' => 'api_website',
                'name' => 'API для сайта агентства',
                'name_uz' => 'Agentlik sayti uchun API',
                'category' => 'api_automation',
                'icon' => '⚡',
                'short_description' => 'REST API для передачи заявок с вашего сайта напрямую в CRM. Полная автоматизация.',
                'short_description_uz' => 'Saytingizdan to\'g\'ridan-to\'g\'ri CRM ga arizalar uzatish uchun REST API. To\'liq avtomatlashtirish.',
                'full_description' => "API VisaCRM позволяет подключить форму заявки на вашем сайте напрямую к CRM. Клиент заполняет форму → данные отправляются по API → заявка создаётся → менеджер получает уведомление.\n\nЭто убирает ручной ввод данных, ускоряет обработку и исключает ошибки.\n\nAPI поддерживает все поля: имя, телефон, email, страна, тип визы, гражданство, UTM-метки, источник, комментарий.\n\nДоступно только на тарифе Enterprise.",
                'full_description_uz' => "VisaCRM API saytingizdagi ariza formasini to'g'ridan-to'g'ri CRM ga ulash imkonini beradi. Mijoz formani to'ldiradi → ma'lumotlar API orqali yuboriladi → ariza yaratiladi.\n\nBu qo'lda ma'lumot kiritishni yo'qotadi, ishlov berishni tezlashtiradi.\n\nFaqat Enterprise tarifida mavjud.",
                'how_it_works' => "1. Получаете API-ключ в настройках VisaCRM (Enterprise)\n2. Интегрируете API в форму на вашем сайте\n3. Клиент заполняет форму на сайте\n4. Данные отправляются POST /api/v1/external/leads\n5. Заявка автоматически создаётся в CRM\n6. Менеджер получает уведомление",
                'how_it_works_uz' => "1. VisaCRM sozlamalarida API-kalitni oling (Enterprise)\n2. API ni saytingizdagi formaga integratsiya qiling\n3. Mijoz saytda formani to'ldiradi\n4. Ma'lumotlar POST /api/v1/external/leads ga yuboriladi\n5. Ariza avtomatik CRM da yaratiladi",
                'when_to_use' => 'Когда у вас есть сайт с формой и нужна автоматическая передача заявок в CRM.',
                'when_not_to_use' => 'Если у вас нет разработчика или сайта.',
                'use_cases' => 'Автоматизация приёма заявок с сайта, интеграция с CMS (WordPress, Tilda).',
                'effectiveness' => 'very_high',
                'effectiveness_factors' => 'Зависит от трафика сайта. API — только канал передачи, не генерации.',
                'complexity' => 'medium',
                'launch_speed' => '3_days',
                'requires_budget' => false,
                'requires_api' => 'yes',
                'enterprise_only' => true,
                'min_plan' => 'enterprise',
                'required_preparation' => 'Сайт с формой, разработчик для интеграции, тариф Enterprise.',
                'expected_result' => '100% заявок с сайта автоматически в CRM. 0 потерянных лидов.',
                'risks' => 'Нужен разработчик для настройки. Ошибки интеграции могут потерять заявки.',
                'best_practices' => 'Тестируйте интеграцию перед запуском. Настройте уведомления об ошибках. Передавайте UTM-метки.',
                'trends' => 'No-code интеграции через Zapier/Make. Webhook вместо polling.',
                'recommended_for' => 'medium',
                'cta_actions' => json_encode(['upgrade', 'learn_more']),
                'sort_order' => 260,
                'is_active' => true,
                'coming_soon' => false,
            ],
            [
                'code' => 'api_meta_leads',
                'name' => 'API для Meta Lead Forms',
                'name_uz' => 'Meta Lead Forms uchun API',
                'category' => 'api_automation',
                'icon' => '🔗',
                'short_description' => 'Автоматическая передача лидов из Instagram/Facebook рекламы напрямую в CRM.',
                'short_description_uz' => 'Instagram/Facebook reklamasidan lidlarni avtomatik CRM ga uzatish.',
                'full_description' => "Meta Lead Forms — это формы заявки прямо внутри Instagram/Facebook. Клиент нажимает кнопку в рекламе → заполняет форму не выходя из приложения.\n\nС API интеграцией эти лиды автоматически попадают в CRM. Без API вам придётся вручную скачивать лиды из Meta Business Suite и вводить в CRM.\n\nИнтеграция экономит часы работы и ускоряет обработку. Быстрая реакция на лид повышает конверсию на 40%.",
                'full_description_uz' => "Meta Lead Forms — Instagram/Facebook ichida ariza formalari. Mijoz reklamada tugmani bosadi → ilovadan chiqmay formani to'ldiradi.\n\nAPI integratsiyasi bilan bu lidlar avtomatik CRM ga tushadi. APIsiz lidlarni qo'lda yuklab olishingiz kerak.",
                'how_it_works' => "1. Настраиваете Meta Lead Form в рекламном кабинете\n2. Подключаете VisaCRM API как webhook для лидов\n3. Клиент видит рекламу → заполняет форму → лид уходит в CRM\n4. Менеджер получает уведомление и обрабатывает\n5. UTM-метки и источник автоматически сохраняются",
                'how_it_works_uz' => "1. Reklama kabinetida Meta Lead Form sozlang\n2. VisaCRM API ni lidlar uchun webhook sifatida ulang\n3. Mijoz reklamani ko'radi → formani to'ldiradi → lid CRM ga tushadi",
                'when_to_use' => 'Когда активно используете Meta рекламу с Lead Forms.',
                'when_not_to_use' => 'Если не используете Meta рекламу.',
                'use_cases' => 'Автоматизация лидов из Instagram/Facebook рекламы.',
                'effectiveness' => 'very_high',
                'effectiveness_factors' => 'Зависит от рекламного бюджета и качества кампаний.',
                'complexity' => 'hard',
                'launch_speed' => '1_week',
                'requires_budget' => true,
                'requires_api' => 'yes',
                'enterprise_only' => true,
                'min_plan' => 'enterprise',
                'required_preparation' => 'Meta Business аккаунт, рекламные кампании, тариф Enterprise.',
                'expected_result' => 'Мгновенная обработка лидов. Конверсия +40% за счёт скорости.',
                'risks' => 'Сложная настройка Meta API. Может потребоваться разработчик.',
                'best_practices' => 'Обрабатывайте лиды в первые 5 минут. Настройте автоответ. Тестируйте формы.',
                'trends' => 'Conversions API от Meta заменяет пиксели. Серверные интеграции.',
                'recommended_for' => 'large',
                'cta_actions' => json_encode(['upgrade', 'learn_more']),
                'sort_order' => 280,
                'is_active' => true,
                'coming_soon' => true,
            ],
            [
                'code' => 'webhook_external',
                'name' => 'Webhook приём лидов',
                'name_uz' => 'Webhook lidlarni qabul qilish',
                'category' => 'api_automation',
                'icon' => '📥',
                'short_description' => 'Универсальный webhook для приёма лидов из любых внешних систем.',
                'short_description_uz' => 'Istalgan tashqi tizimlardan lidlarni qabul qilish uchun universal webhook.',
                'full_description' => "Webhook — универсальный способ передачи данных. Любая внешняя система может отправить POST-запрос на ваш webhook URL, и заявка автоматически создастся в CRM.\n\nЭто позволяет принимать лиды откуда угодно: с лендингов, из CMS, из рекламных платформ, из внешних форм, из других CRM при миграции.\n\nWebhook поддерживает: JSON payload, mapping полей, валидацию, дедупликацию.",
                'full_description_uz' => "Webhook — ma'lumotlarni uzatishning universal usuli. Har qanday tashqi tizim webhook URL ga POST-so'rov yuborishi mumkin va ariza avtomatik CRM da yaratiladi.\n\nBu lidlarni istalgan joydan qabul qilish imkonini beradi: lendinglardan, CMS dan, reklama platformalaridan.",
                'how_it_works' => "1. Получаете webhook URL в настройках VisaCRM\n2. Настраиваете внешнюю систему на отправку данных\n3. Определяете mapping полей (JSON → поля CRM)\n4. Внешняя система отправляет данные → заявка создаётся\n5. Менеджер обрабатывает заявку",
                'how_it_works_uz' => "1. VisaCRM sozlamalarida webhook URL oling\n2. Tashqi tizimni ma'lumotlar yuborishga sozlang\n3. Maydonlar xaritasini belgilang (JSON → CRM maydonlari)\n4. Tashqi tizim ma'lumot yuboradi → ariza yaratiladi",
                'when_to_use' => 'Когда нужно принимать лиды из нестандартных источников.',
                'when_not_to_use' => 'Если достаточно стандартных каналов (Telegram, форма VisaCRM).',
                'use_cases' => 'Интеграция с лендингами, CMS, внешними формами, миграция из других CRM.',
                'effectiveness' => 'high',
                'effectiveness_factors' => 'Зависит от источника лидов. Webhook — только транспорт.',
                'complexity' => 'medium',
                'launch_speed' => '3_days',
                'requires_budget' => false,
                'requires_api' => 'yes',
                'enterprise_only' => true,
                'min_plan' => 'enterprise',
                'required_preparation' => 'Внешняя система с поддержкой webhook, тариф Enterprise.',
                'expected_result' => '100% лидов из внешних систем автоматически в CRM.',
                'risks' => 'Ошибки в mapping полей. Нужен мониторинг доставки.',
                'best_practices' => 'Тестируйте webhook до запуска. Настройте retry при ошибках. Логируйте все запросы.',
                'trends' => 'Event-driven архитектура. Real-time обработка вместо batch.',
                'recommended_for' => 'large',
                'cta_actions' => json_encode(['upgrade', 'learn_more']),
                'sort_order' => 290,
                'is_active' => true,
                'coming_soon' => false,
            ],
            [
                'code' => 'zapier_make',
                'name' => 'Zapier / Make / n8n',
                'name_uz' => 'Zapier / Make / n8n',
                'category' => 'api_automation',
                'icon' => '🔧',
                'short_description' => 'No-code интеграции: подключите 5000+ сервисов к CRM без программирования.',
                'short_description_uz' => 'No-code integratsiyalar: 5000+ xizmatni dasturlashsiz CRM ga ulang.',
                'full_description' => "Zapier, Make (бывший Integromat) и n8n — платформы no-code автоматизации. Они позволяют связать VisaCRM с тысячами сервисов без написания кода.\n\nПримеры: Google Forms → CRM, Typeform → CRM, Calendly → CRM, Excel → CRM, Gmail → CRM.\n\nЭто будущее интеграций: вместо разработки каждой интеграции — универсальный коннектор.",
                'full_description_uz' => "Zapier, Make va n8n — no-code avtomatlashtirish platformalari. Ular VisaCRM ni kod yozmasdan minglab xizmatlar bilan bog'lash imkonini beradi.\n\nMisollar: Google Forms → CRM, Typeform → CRM, Calendly → CRM.",
                'how_it_works' => "1. Регистрируетесь в Zapier/Make/n8n\n2. Подключаете VisaCRM через API-ключ\n3. Создаёте сценарий: Источник → VisaCRM\n4. Тестируете\n5. Данные автоматически передаются в CRM",
                'how_it_works_uz' => "1. Zapier/Make/n8n da ro'yxatdan o'ting\n2. API-kalit orqali VisaCRM ni ulang\n3. Stsenariy yarating: Manba → VisaCRM\n4. Test qiling",
                'when_to_use' => 'Когда нужна интеграция с внешним сервисом без программирования.',
                'when_not_to_use' => 'Если хватает встроенных каналов VisaCRM.',
                'use_cases' => 'Google Forms → CRM, Calendly → CRM, Typeform → CRM, Excel импорт.',
                'effectiveness' => 'high',
                'effectiveness_factors' => 'Зависит от выбранных сервисов и качества настройки сценариев.',
                'complexity' => 'medium',
                'launch_speed' => '3_days',
                'requires_budget' => true,
                'requires_api' => 'yes',
                'enterprise_only' => true,
                'min_plan' => 'enterprise',
                'required_preparation' => 'Аккаунт Zapier/Make, API-ключ VisaCRM (Enterprise).',
                'expected_result' => 'Автоматизация любых рутинных процессов передачи данных.',
                'risks' => 'Zapier/Make платные. Сценарии могут ломаться при изменениях в API.',
                'best_practices' => 'Начните с простого сценария. Настройте уведомления об ошибках. Тестируйте регулярно.',
                'trends' => 'AI в no-code платформах. Автогенерация сценариев. n8n как open-source альтернатива.',
                'recommended_for' => 'large',
                'cta_actions' => json_encode(['upgrade', 'learn_more']),
                'sort_order' => 300,
                'is_active' => true,
                'coming_soon' => true,
            ],
        ];
    }
}
