<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class WorldCountriesSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();
        $countries = array_merge(
            $this->visaFreeCountries(),
            $this->visaOnArrivalCountries(),
            $this->evisaCountries(),
            $this->visaRequiredCountries(),
        );

        // Нормализовать все записи к единому набору ключей (PostgreSQL upsert требует)
        $defaults = [
            'country_code' => '', 'name' => '', 'name_uz' => null, 'flag_emoji' => '🌍',
            'visa_regime' => 'visa_required', 'visa_free_days' => null, 'visa_on_arrival_days' => null,
            'evisa_available' => false, 'evisa_url' => null, 'evisa_processing_days' => null,
            'invitation_required' => false, 'hotel_booking_required' => false,
            'insurance_required' => false, 'bank_statement_required' => true,
            'return_ticket_required' => false,
            'visa_fee_usd' => null, 'evisa_fee_usd' => null,
            'avg_flight_cost_usd' => null, 'avg_hotel_per_night_usd' => null,
            'is_popular' => false, 'is_high_approval' => false, 'is_high_refusal' => false,
            'continent' => null, 'risk_level' => 'medium',
            'sort_order' => 0, 'is_active' => true,
        ];

        foreach ($countries as $i => &$c) {
            $c = array_merge($defaults, $c);
            $c['sort_order'] = $c['sort_order'] ?: ($i + 1);
            $c['created_at'] = $now;
            $c['updated_at'] = $now;
        }
        unset($c);

        // Upsert по country_code — безопасно запускать повторно
        $updateColumns = [
            'name', 'name_uz', 'flag_emoji', 'visa_regime', 'visa_free_days',
            'visa_on_arrival_days', 'evisa_available', 'evisa_url', 'evisa_processing_days',
            'invitation_required', 'hotel_booking_required', 'insurance_required',
            'bank_statement_required', 'return_ticket_required',
            'visa_fee_usd', 'evisa_fee_usd', 'avg_flight_cost_usd', 'avg_hotel_per_night_usd',
            'is_popular', 'is_high_approval', 'is_high_refusal',
            'continent', 'risk_level', 'sort_order', 'is_active', 'updated_at',
        ];

        // Batch upsert по 50 записей
        foreach (array_chunk($countries, 50) as $chunk) {
            DB::table('portal_countries')->upsert($chunk, ['country_code'], $updateColumns);
        }

        $this->command->info('WorldCountriesSeeder: ' . count($countries) . ' стран загружено.');
    }

    // =========================================================================
    // Безвизовые страны для граждан Узбекистана
    // =========================================================================
    private function visaFreeCountries(): array
    {
        return [
            // СНГ
            ['country_code' => 'AZ', 'name' => 'Азербайджан',   'name_uz' => 'Ozarbayjon',     'flag_emoji' => '🇦🇿', 'visa_regime' => 'visa_free', 'visa_free_days' => 90,  'continent' => 'Asia',          'risk_level' => 'low', 'is_popular' => true,  'avg_flight_cost_usd' => 200, 'avg_hotel_per_night_usd' => 40],
            ['country_code' => 'AM', 'name' => 'Армения',       'name_uz' => 'Armaniston',     'flag_emoji' => '🇦🇲', 'visa_regime' => 'visa_free', 'visa_free_days' => 90,  'continent' => 'Asia',          'risk_level' => 'low', 'is_popular' => false, 'avg_flight_cost_usd' => 220, 'avg_hotel_per_night_usd' => 35],
            ['country_code' => 'BY', 'name' => 'Беларусь',      'name_uz' => 'Belarus',        'flag_emoji' => '🇧🇾', 'visa_regime' => 'visa_free', 'visa_free_days' => 90,  'continent' => 'Europe',        'risk_level' => 'low', 'is_popular' => false, 'avg_flight_cost_usd' => 300, 'avg_hotel_per_night_usd' => 40],
            ['country_code' => 'GE', 'name' => 'Грузия',        'name_uz' => 'Gruziya',        'flag_emoji' => '🇬🇪', 'visa_regime' => 'visa_free', 'visa_free_days' => 365, 'continent' => 'Asia',          'risk_level' => 'low', 'is_popular' => true,  'avg_flight_cost_usd' => 250, 'avg_hotel_per_night_usd' => 35],
            ['country_code' => 'KZ', 'name' => 'Казахстан',     'name_uz' => "Qozog'iston",    'flag_emoji' => '🇰🇿', 'visa_regime' => 'visa_free', 'visa_free_days' => 30,  'continent' => 'Asia',          'risk_level' => 'low', 'is_popular' => true,  'avg_flight_cost_usd' => 80,  'avg_hotel_per_night_usd' => 35],
            ['country_code' => 'KG', 'name' => 'Кыргызстан',    'name_uz' => "Qirg'iziston",   'flag_emoji' => '🇰🇬', 'visa_regime' => 'visa_free', 'visa_free_days' => 60,  'continent' => 'Asia',          'risk_level' => 'low', 'is_popular' => true,  'avg_flight_cost_usd' => 100, 'avg_hotel_per_night_usd' => 25],
            ['country_code' => 'MD', 'name' => 'Молдова',       'name_uz' => 'Moldova',        'flag_emoji' => '🇲🇩', 'visa_regime' => 'visa_free', 'visa_free_days' => 90,  'continent' => 'Europe',        'risk_level' => 'low', 'is_popular' => false, 'avg_flight_cost_usd' => 350, 'avg_hotel_per_night_usd' => 30],
            ['country_code' => 'RU', 'name' => 'Россия',        'name_uz' => 'Rossiya',        'flag_emoji' => '🇷🇺', 'visa_regime' => 'visa_free', 'visa_free_days' => 90,  'continent' => 'Europe',        'risk_level' => 'low', 'is_popular' => true,  'avg_flight_cost_usd' => 150, 'avg_hotel_per_night_usd' => 50],
            ['country_code' => 'TJ', 'name' => 'Таджикистан',   'name_uz' => 'Tojikiston',     'flag_emoji' => '🇹🇯', 'visa_regime' => 'visa_free', 'visa_free_days' => 90,  'continent' => 'Asia',          'risk_level' => 'low', 'is_popular' => false, 'avg_flight_cost_usd' => 100, 'avg_hotel_per_night_usd' => 20],
            ['country_code' => 'TM', 'name' => 'Туркменистан',  'name_uz' => 'Turkmaniston',   'flag_emoji' => '🇹🇲', 'visa_regime' => 'visa_free', 'visa_free_days' => 30,  'continent' => 'Asia',          'risk_level' => 'low', 'is_popular' => false, 'avg_flight_cost_usd' => 150, 'avg_hotel_per_night_usd' => 30],
            ['country_code' => 'UA', 'name' => 'Украина',       'name_uz' => 'Ukraina',        'flag_emoji' => '🇺🇦', 'visa_regime' => 'visa_free', 'visa_free_days' => 90,  'continent' => 'Europe',        'risk_level' => 'low', 'is_popular' => false, 'avg_flight_cost_usd' => 300, 'avg_hotel_per_night_usd' => 30],

            // Турция и Азия (безвизовые)
            ['country_code' => 'TR', 'name' => 'Турция',        'name_uz' => 'Turkiya',        'flag_emoji' => '🇹🇷', 'visa_regime' => 'visa_free', 'visa_free_days' => 30,  'continent' => 'Europe',        'risk_level' => 'low', 'is_popular' => true,  'avg_flight_cost_usd' => 250, 'avg_hotel_per_night_usd' => 50],
            ['country_code' => 'MY', 'name' => 'Малайзия',      'name_uz' => 'Malayziya',      'flag_emoji' => '🇲🇾', 'visa_regime' => 'visa_free', 'visa_free_days' => 30,  'continent' => 'Asia',          'risk_level' => 'low', 'is_popular' => true,  'avg_flight_cost_usd' => 500, 'avg_hotel_per_night_usd' => 40],
            ['country_code' => 'ID', 'name' => 'Индонезия',     'name_uz' => 'Indoneziya',     'flag_emoji' => '🇮🇩', 'visa_regime' => 'visa_free', 'visa_free_days' => 30,  'continent' => 'Asia',          'risk_level' => 'low', 'is_popular' => true,  'avg_flight_cost_usd' => 550, 'avg_hotel_per_night_usd' => 30],
            ['country_code' => 'KR', 'name' => 'Южная Корея',   'name_uz' => 'Janubiy Koreya', 'flag_emoji' => '🇰🇷', 'visa_regime' => 'visa_free', 'visa_free_days' => 30,  'continent' => 'Asia',          'risk_level' => 'low', 'is_popular' => true,  'avg_flight_cost_usd' => 600, 'avg_hotel_per_night_usd' => 60],
            ['country_code' => 'SG', 'name' => 'Сингапур',      'name_uz' => 'Singapur',       'flag_emoji' => '🇸🇬', 'visa_regime' => 'visa_free', 'visa_free_days' => 30,  'continent' => 'Asia',          'risk_level' => 'low', 'is_popular' => false, 'avg_flight_cost_usd' => 600, 'avg_hotel_per_night_usd' => 80],
            ['country_code' => 'MN', 'name' => 'Монголия',      'name_uz' => "Mo'g'uliston",   'flag_emoji' => '🇲🇳', 'visa_regime' => 'visa_free', 'visa_free_days' => 30,  'continent' => 'Asia',          'risk_level' => 'low', 'is_popular' => false, 'avg_flight_cost_usd' => 400, 'avg_hotel_per_night_usd' => 30],

            // Другие безвизовые
            ['country_code' => 'RS', 'name' => 'Сербия',        'name_uz' => 'Serbiya',        'flag_emoji' => '🇷🇸', 'visa_regime' => 'visa_free', 'visa_free_days' => 30,  'continent' => 'Europe',        'risk_level' => 'low', 'is_popular' => false, 'avg_flight_cost_usd' => 350, 'avg_hotel_per_night_usd' => 35],
            ['country_code' => 'BA', 'name' => 'Босния и Герцеговина', 'name_uz' => 'Bosniya va Gersegovina', 'flag_emoji' => '🇧🇦', 'visa_regime' => 'visa_free', 'visa_free_days' => 30, 'continent' => 'Europe', 'risk_level' => 'low', 'is_popular' => false, 'avg_flight_cost_usd' => 400, 'avg_hotel_per_night_usd' => 30],
            ['country_code' => 'ME', 'name' => 'Черногория',    'name_uz' => 'Chernogoriya',   'flag_emoji' => '🇲🇪', 'visa_regime' => 'visa_free', 'visa_free_days' => 30,  'continent' => 'Europe',        'risk_level' => 'low', 'is_popular' => false, 'avg_flight_cost_usd' => 400, 'avg_hotel_per_night_usd' => 40],
            ['country_code' => 'MK', 'name' => 'Северная Македония', 'name_uz' => 'Shimoliy Makedoniya', 'flag_emoji' => '🇲🇰', 'visa_regime' => 'visa_free', 'visa_free_days' => 90, 'continent' => 'Europe', 'risk_level' => 'low', 'is_popular' => false, 'avg_flight_cost_usd' => 380, 'avg_hotel_per_night_usd' => 30],
            ['country_code' => 'AL', 'name' => 'Албания',       'name_uz' => 'Albaniya',       'flag_emoji' => '🇦🇱', 'visa_regime' => 'visa_free', 'visa_free_days' => 90,  'continent' => 'Europe',        'risk_level' => 'low', 'is_popular' => false, 'avg_flight_cost_usd' => 400, 'avg_hotel_per_night_usd' => 30],
            ['country_code' => 'DO', 'name' => 'Доминиканская Республика', 'name_uz' => 'Dominikan Respublikasi', 'flag_emoji' => '🇩🇴', 'visa_regime' => 'visa_free', 'visa_free_days' => 30, 'continent' => 'North America', 'risk_level' => 'low', 'is_popular' => false, 'avg_flight_cost_usd' => 900, 'avg_hotel_per_night_usd' => 60],
            ['country_code' => 'PA', 'name' => 'Панама',        'name_uz' => 'Panama',         'flag_emoji' => '🇵🇦', 'visa_regime' => 'visa_free', 'visa_free_days' => 90,  'continent' => 'North America', 'risk_level' => 'low', 'is_popular' => false, 'avg_flight_cost_usd' => 1000, 'avg_hotel_per_night_usd' => 55],
            ['country_code' => 'EC', 'name' => 'Эквадор',       'name_uz' => 'Ekvador',        'flag_emoji' => '🇪🇨', 'visa_regime' => 'visa_free', 'visa_free_days' => 90,  'continent' => 'South America', 'risk_level' => 'low', 'is_popular' => false, 'avg_flight_cost_usd' => 1100, 'avg_hotel_per_night_usd' => 35],
            ['country_code' => 'HN', 'name' => 'Гондурас',      'name_uz' => 'Gonduras',       'flag_emoji' => '🇭🇳', 'visa_regime' => 'visa_free', 'visa_free_days' => 90,  'continent' => 'North America', 'risk_level' => 'low', 'is_popular' => false, 'avg_flight_cost_usd' => 1000, 'avg_hotel_per_night_usd' => 30],
            ['country_code' => 'NI', 'name' => 'Никарагуа',     'name_uz' => 'Nikaragua',      'flag_emoji' => '🇳🇮', 'visa_regime' => 'visa_free', 'visa_free_days' => 90,  'continent' => 'North America', 'risk_level' => 'low', 'is_popular' => false, 'avg_flight_cost_usd' => 1000, 'avg_hotel_per_night_usd' => 25],
            ['country_code' => 'HT', 'name' => 'Гаити',         'name_uz' => 'Gaiti',          'flag_emoji' => '🇭🇹', 'visa_regime' => 'visa_free', 'visa_free_days' => 90,  'continent' => 'North America', 'risk_level' => 'medium', 'is_popular' => false, 'avg_flight_cost_usd' => 1100, 'avg_hotel_per_night_usd' => 40],
            ['country_code' => 'DM', 'name' => 'Доминика',      'name_uz' => 'Dominika',       'flag_emoji' => '🇩🇲', 'visa_regime' => 'visa_free', 'visa_free_days' => 21,  'continent' => 'North America', 'risk_level' => 'low', 'is_popular' => false, 'avg_flight_cost_usd' => 1200, 'avg_hotel_per_night_usd' => 70],
            ['country_code' => 'BB', 'name' => 'Барбадос',      'name_uz' => 'Barbados',       'flag_emoji' => '🇧🇧', 'visa_regime' => 'visa_free', 'visa_free_days' => 28,  'continent' => 'North America', 'risk_level' => 'low', 'is_popular' => false, 'avg_flight_cost_usd' => 1200, 'avg_hotel_per_night_usd' => 80],
            ['country_code' => 'VC', 'name' => 'Сент-Винсент',  'name_uz' => 'Sent-Vinsent',   'flag_emoji' => '🇻🇨', 'visa_regime' => 'visa_free', 'visa_free_days' => 30,  'continent' => 'North America', 'risk_level' => 'low', 'is_popular' => false, 'avg_flight_cost_usd' => 1300, 'avg_hotel_per_night_usd' => 70],
            ['country_code' => 'MS', 'name' => 'Микронезия',    'name_uz' => 'Mikroneziya',    'flag_emoji' => '🇫🇲', 'visa_regime' => 'visa_free', 'visa_free_days' => 30,  'continent' => 'Oceania',       'risk_level' => 'low', 'is_popular' => false, 'avg_flight_cost_usd' => 1500, 'avg_hotel_per_night_usd' => 60],
        ];
    }

    // =========================================================================
    // Visa on arrival
    // =========================================================================
    private function visaOnArrivalCountries(): array
    {
        return [
            ['country_code' => 'IR', 'name' => 'Иран',          'name_uz' => 'Eron',           'flag_emoji' => '🇮🇷', 'visa_regime' => 'visa_on_arrival', 'visa_on_arrival_days' => 30, 'visa_fee_usd' => 40,  'continent' => 'Asia',    'risk_level' => 'low',    'is_popular' => false, 'avg_flight_cost_usd' => 250, 'avg_hotel_per_night_usd' => 25],
            ['country_code' => 'MV', 'name' => 'Мальдивы',      'name_uz' => 'Maldiv orollari','flag_emoji' => '🇲🇻', 'visa_regime' => 'visa_on_arrival', 'visa_on_arrival_days' => 30, 'visa_fee_usd' => 0,   'continent' => 'Asia',    'risk_level' => 'low',    'is_popular' => true,  'avg_flight_cost_usd' => 600, 'avg_hotel_per_night_usd' => 100],
            ['country_code' => 'KH', 'name' => 'Камбоджа',      'name_uz' => 'Kambodja',       'flag_emoji' => '🇰🇭', 'visa_regime' => 'visa_on_arrival', 'visa_on_arrival_days' => 30, 'visa_fee_usd' => 30,  'continent' => 'Asia',    'risk_level' => 'low',    'is_popular' => false, 'avg_flight_cost_usd' => 500, 'avg_hotel_per_night_usd' => 20],
            ['country_code' => 'LA', 'name' => 'Лаос',          'name_uz' => 'Laos',           'flag_emoji' => '🇱🇦', 'visa_regime' => 'visa_on_arrival', 'visa_on_arrival_days' => 30, 'visa_fee_usd' => 30,  'continent' => 'Asia',    'risk_level' => 'low',    'is_popular' => false, 'avg_flight_cost_usd' => 550, 'avg_hotel_per_night_usd' => 20],
            ['country_code' => 'BD', 'name' => 'Бангладеш',     'name_uz' => 'Bangladesh',     'flag_emoji' => '🇧🇩', 'visa_regime' => 'visa_on_arrival', 'visa_on_arrival_days' => 30, 'visa_fee_usd' => 50,  'continent' => 'Asia',    'risk_level' => 'low',    'is_popular' => false, 'avg_flight_cost_usd' => 400, 'avg_hotel_per_night_usd' => 20],
            ['country_code' => 'NP', 'name' => 'Непал',         'name_uz' => 'Nepal',          'flag_emoji' => '🇳🇵', 'visa_regime' => 'visa_on_arrival', 'visa_on_arrival_days' => 90, 'visa_fee_usd' => 30,  'continent' => 'Asia',    'risk_level' => 'low',    'is_popular' => false, 'avg_flight_cost_usd' => 400, 'avg_hotel_per_night_usd' => 20],
            ['country_code' => 'MM', 'name' => 'Мьянма',        'name_uz' => 'Myanma',         'flag_emoji' => '🇲🇲', 'visa_regime' => 'visa_on_arrival', 'visa_on_arrival_days' => 28, 'visa_fee_usd' => 50,  'continent' => 'Asia',    'risk_level' => 'medium', 'is_popular' => false, 'avg_flight_cost_usd' => 500, 'avg_hotel_per_night_usd' => 25],
            ['country_code' => 'TL', 'name' => 'Восточный Тимор','name_uz' => "Sharqiy Timor",  'flag_emoji' => '🇹🇱', 'visa_regime' => 'visa_on_arrival', 'visa_on_arrival_days' => 30, 'visa_fee_usd' => 30, 'continent' => 'Asia',    'risk_level' => 'low',    'is_popular' => false, 'avg_flight_cost_usd' => 700, 'avg_hotel_per_night_usd' => 30],
            ['country_code' => 'MG', 'name' => 'Мадагаскар',    'name_uz' => 'Madagaskar',     'flag_emoji' => '🇲🇬', 'visa_regime' => 'visa_on_arrival', 'visa_on_arrival_days' => 90, 'visa_fee_usd' => 35,  'continent' => 'Africa',  'risk_level' => 'low',    'is_popular' => false, 'avg_flight_cost_usd' => 800, 'avg_hotel_per_night_usd' => 30],
            ['country_code' => 'MZ', 'name' => 'Мозамбик',      'name_uz' => 'Mozambik',       'flag_emoji' => '🇲🇿', 'visa_regime' => 'visa_on_arrival', 'visa_on_arrival_days' => 30, 'visa_fee_usd' => 50,  'continent' => 'Africa',  'risk_level' => 'medium', 'is_popular' => false, 'avg_flight_cost_usd' => 800, 'avg_hotel_per_night_usd' => 30],
            ['country_code' => 'RW', 'name' => 'Руанда',        'name_uz' => 'Ruanda',         'flag_emoji' => '🇷🇼', 'visa_regime' => 'visa_on_arrival', 'visa_on_arrival_days' => 30, 'visa_fee_usd' => 30,  'continent' => 'Africa',  'risk_level' => 'low',    'is_popular' => false, 'avg_flight_cost_usd' => 750, 'avg_hotel_per_night_usd' => 40],
            ['country_code' => 'SO', 'name' => 'Сомали',        'name_uz' => 'Somali',         'flag_emoji' => '🇸🇴', 'visa_regime' => 'visa_on_arrival', 'visa_on_arrival_days' => 30, 'visa_fee_usd' => 60,  'continent' => 'Africa',  'risk_level' => 'high',   'is_popular' => false, 'avg_flight_cost_usd' => 700, 'avg_hotel_per_night_usd' => 40],
            ['country_code' => 'TG', 'name' => 'Того',          'name_uz' => 'Togo',           'flag_emoji' => '🇹🇬', 'visa_regime' => 'visa_on_arrival', 'visa_on_arrival_days' => 7,  'visa_fee_usd' => 25,  'continent' => 'Africa',  'risk_level' => 'low',    'is_popular' => false, 'avg_flight_cost_usd' => 800, 'avg_hotel_per_night_usd' => 25],
            ['country_code' => 'UG', 'name' => 'Уганда',        'name_uz' => 'Uganda',         'flag_emoji' => '🇺🇬', 'visa_regime' => 'visa_on_arrival', 'visa_on_arrival_days' => 90, 'visa_fee_usd' => 50,  'continent' => 'Africa',  'risk_level' => 'low',    'is_popular' => false, 'avg_flight_cost_usd' => 700, 'avg_hotel_per_night_usd' => 30],
            ['country_code' => 'CV', 'name' => 'Кабо-Верде',    'name_uz' => 'Kabo-Verde',     'flag_emoji' => '🇨🇻', 'visa_regime' => 'visa_on_arrival', 'visa_on_arrival_days' => 30, 'visa_fee_usd' => 25,  'continent' => 'Africa',  'risk_level' => 'low',    'is_popular' => false, 'avg_flight_cost_usd' => 900, 'avg_hotel_per_night_usd' => 40],
            ['country_code' => 'KM', 'name' => 'Коморы',        'name_uz' => 'Komor orollari', 'flag_emoji' => '🇰🇲', 'visa_regime' => 'visa_on_arrival', 'visa_on_arrival_days' => 45, 'visa_fee_usd' => 50,  'continent' => 'Africa',  'risk_level' => 'low',    'is_popular' => false, 'avg_flight_cost_usd' => 900, 'avg_hotel_per_night_usd' => 40],
            ['country_code' => 'DJ', 'name' => 'Джибути',       'name_uz' => 'Jibuti',         'flag_emoji' => '🇩🇯', 'visa_regime' => 'visa_on_arrival', 'visa_on_arrival_days' => 31, 'visa_fee_usd' => 30,  'continent' => 'Africa',  'risk_level' => 'low',    'is_popular' => false, 'avg_flight_cost_usd' => 700, 'avg_hotel_per_night_usd' => 50],
            ['country_code' => 'MW', 'name' => 'Малави',        'name_uz' => 'Malavi',         'flag_emoji' => '🇲🇼', 'visa_regime' => 'visa_on_arrival', 'visa_on_arrival_days' => 30, 'visa_fee_usd' => 75,  'continent' => 'Africa',  'risk_level' => 'low',    'is_popular' => false, 'avg_flight_cost_usd' => 800, 'avg_hotel_per_night_usd' => 25],
            ['country_code' => 'MR', 'name' => 'Мавритания',    'name_uz' => 'Mavritaniya',    'flag_emoji' => '🇲🇷', 'visa_regime' => 'visa_on_arrival', 'visa_on_arrival_days' => 30, 'visa_fee_usd' => 55,  'continent' => 'Africa',  'risk_level' => 'low',    'is_popular' => false, 'avg_flight_cost_usd' => 800, 'avg_hotel_per_night_usd' => 30],
            ['country_code' => 'SC', 'name' => 'Сейшелы',       'name_uz' => 'Seyshel orollari','flag_emoji' => '🇸🇨', 'visa_regime' => 'visa_on_arrival', 'visa_on_arrival_days' => 90, 'visa_fee_usd' => 0, 'continent' => 'Africa',  'risk_level' => 'low',    'is_popular' => false, 'avg_flight_cost_usd' => 800, 'avg_hotel_per_night_usd' => 120],
            ['country_code' => 'SB', 'name' => 'Соломоновы Острова', 'name_uz' => 'Solomon orollari', 'flag_emoji' => '🇸🇧', 'visa_regime' => 'visa_on_arrival', 'visa_on_arrival_days' => 90, 'visa_fee_usd' => 0, 'continent' => 'Oceania', 'risk_level' => 'low', 'is_popular' => false, 'avg_flight_cost_usd' => 1500, 'avg_hotel_per_night_usd' => 50],
            ['country_code' => 'TV', 'name' => 'Тувалу',        'name_uz' => 'Tuvalu',         'flag_emoji' => '🇹🇻', 'visa_regime' => 'visa_on_arrival', 'visa_on_arrival_days' => 30, 'visa_fee_usd' => 0,   'continent' => 'Oceania', 'risk_level' => 'low',    'is_popular' => false, 'avg_flight_cost_usd' => 1500, 'avg_hotel_per_night_usd' => 60],
            ['country_code' => 'WS', 'name' => 'Самоа',         'name_uz' => 'Samoa',          'flag_emoji' => '🇼🇸', 'visa_regime' => 'visa_on_arrival', 'visa_on_arrival_days' => 60, 'visa_fee_usd' => 0,   'continent' => 'Oceania', 'risk_level' => 'low',    'is_popular' => false, 'avg_flight_cost_usd' => 1500, 'avg_hotel_per_night_usd' => 50],
            ['country_code' => 'JO', 'name' => 'Иордания',      'name_uz' => 'Iordaniya',      'flag_emoji' => '🇯🇴', 'visa_regime' => 'visa_on_arrival', 'visa_on_arrival_days' => 30, 'visa_fee_usd' => 40,  'continent' => 'Asia',    'risk_level' => 'low',    'is_popular' => false, 'avg_flight_cost_usd' => 400, 'avg_hotel_per_night_usd' => 50],
            ['country_code' => 'LB', 'name' => 'Ливан',         'name_uz' => 'Livan',          'flag_emoji' => '🇱🇧', 'visa_regime' => 'visa_on_arrival', 'visa_on_arrival_days' => 30, 'visa_fee_usd' => 0,   'continent' => 'Asia',    'risk_level' => 'medium', 'is_popular' => false, 'avg_flight_cost_usd' => 400, 'avg_hotel_per_night_usd' => 50],
            ['country_code' => 'BN', 'name' => 'Бруней',        'name_uz' => 'Bruney',         'flag_emoji' => '🇧🇳', 'visa_regime' => 'visa_on_arrival', 'visa_on_arrival_days' => 14, 'visa_fee_usd' => 20,  'continent' => 'Asia',    'risk_level' => 'low',    'is_popular' => false, 'avg_flight_cost_usd' => 600, 'avg_hotel_per_night_usd' => 50],
            ['country_code' => 'PW', 'name' => 'Палау',         'name_uz' => 'Palau',          'flag_emoji' => '🇵🇼', 'visa_regime' => 'visa_on_arrival', 'visa_on_arrival_days' => 30, 'visa_fee_usd' => 0,   'continent' => 'Oceania', 'risk_level' => 'low',    'is_popular' => false, 'avg_flight_cost_usd' => 1500, 'avg_hotel_per_night_usd' => 80],
            ['country_code' => 'MH', 'name' => 'Маршалловы Острова', 'name_uz' => 'Marshall orollari', 'flag_emoji' => '🇲🇭', 'visa_regime' => 'visa_on_arrival', 'visa_on_arrival_days' => 30, 'visa_fee_usd' => 0, 'continent' => 'Oceania', 'risk_level' => 'low', 'is_popular' => false, 'avg_flight_cost_usd' => 1500, 'avg_hotel_per_night_usd' => 60],
        ];
    }

    // =========================================================================
    // eVisa
    // =========================================================================
    private function evisaCountries(): array
    {
        return [
            ['country_code' => 'AE', 'name' => 'ОАЭ',          'name_uz' => 'BAA',            'flag_emoji' => '🇦🇪', 'visa_regime' => 'evisa', 'evisa_available' => true, 'evisa_processing_days' => 4,  'evisa_fee_usd' => 90,  'continent' => 'Asia',    'risk_level' => 'low',    'is_popular' => true,  'avg_flight_cost_usd' => 300, 'avg_hotel_per_night_usd' => 80],
            ['country_code' => 'IN', 'name' => 'Индия',         'name_uz' => 'Hindiston',      'flag_emoji' => '🇮🇳', 'visa_regime' => 'evisa', 'evisa_available' => true, 'evisa_processing_days' => 5,  'evisa_fee_usd' => 25,  'continent' => 'Asia',    'risk_level' => 'low',    'is_popular' => true,  'evisa_url' => 'https://indianvisaonline.gov.in', 'avg_flight_cost_usd' => 350, 'avg_hotel_per_night_usd' => 25],
            ['country_code' => 'LK', 'name' => 'Шри-Ланка',    'name_uz' => 'Shri-Lanka',     'flag_emoji' => '🇱🇰', 'visa_regime' => 'evisa', 'evisa_available' => true, 'evisa_processing_days' => 3,  'evisa_fee_usd' => 50,  'continent' => 'Asia',    'risk_level' => 'low',    'is_popular' => false, 'evisa_url' => 'https://www.srilankaevisa.lk', 'avg_flight_cost_usd' => 450, 'avg_hotel_per_night_usd' => 30],
            ['country_code' => 'TH', 'name' => 'Таиланд',      'name_uz' => 'Tailand',        'flag_emoji' => '🇹🇭', 'visa_regime' => 'evisa', 'evisa_available' => true, 'evisa_processing_days' => 5,  'evisa_fee_usd' => 35,  'continent' => 'Asia',    'risk_level' => 'low',    'is_popular' => true,  'avg_flight_cost_usd' => 450, 'avg_hotel_per_night_usd' => 30],
            ['country_code' => 'VN', 'name' => 'Вьетнам',       'name_uz' => 'Vyetnam',        'flag_emoji' => '🇻🇳', 'visa_regime' => 'evisa', 'evisa_available' => true, 'evisa_processing_days' => 3,  'evisa_fee_usd' => 25,  'continent' => 'Asia',    'risk_level' => 'low',    'is_popular' => true,  'evisa_url' => 'https://evisa.xuatnhapcanh.gov.vn', 'avg_flight_cost_usd' => 450, 'avg_hotel_per_night_usd' => 25],
            ['country_code' => 'AU', 'name' => 'Австралия',     'name_uz' => 'Avstraliya',     'flag_emoji' => '🇦🇺', 'visa_regime' => 'evisa', 'evisa_available' => true, 'evisa_processing_days' => 20, 'evisa_fee_usd' => 145, 'continent' => 'Oceania', 'risk_level' => 'high',   'is_popular' => false, 'insurance_required' => true, 'bank_statement_required' => true, 'avg_flight_cost_usd' => 1000, 'avg_hotel_per_night_usd' => 100],
            ['country_code' => 'NZ', 'name' => 'Новая Зеландия','name_uz' => 'Yangi Zelandiya','flag_emoji' => '🇳🇿', 'visa_regime' => 'evisa', 'evisa_available' => true, 'evisa_processing_days' => 20, 'evisa_fee_usd' => 165, 'continent' => 'Oceania', 'risk_level' => 'high',   'is_popular' => false, 'insurance_required' => true, 'bank_statement_required' => true, 'avg_flight_cost_usd' => 1200, 'avg_hotel_per_night_usd' => 90],
            ['country_code' => 'BH', 'name' => 'Бахрейн',      'name_uz' => 'Bahrayn',        'flag_emoji' => '🇧🇭', 'visa_regime' => 'evisa', 'evisa_available' => true, 'evisa_processing_days' => 3,  'evisa_fee_usd' => 29,  'continent' => 'Asia',    'risk_level' => 'low',    'is_popular' => false, 'avg_flight_cost_usd' => 350, 'avg_hotel_per_night_usd' => 70],
            ['country_code' => 'OM', 'name' => 'Оман',          'name_uz' => 'Ummon',          'flag_emoji' => '🇴🇲', 'visa_regime' => 'evisa', 'evisa_available' => true, 'evisa_processing_days' => 5,  'evisa_fee_usd' => 20,  'continent' => 'Asia',    'risk_level' => 'low',    'is_popular' => false, 'avg_flight_cost_usd' => 350, 'avg_hotel_per_night_usd' => 60],
            ['country_code' => 'QA', 'name' => 'Катар',         'name_uz' => 'Qatar',          'flag_emoji' => '🇶🇦', 'visa_regime' => 'evisa', 'evisa_available' => true, 'evisa_processing_days' => 4,  'evisa_fee_usd' => 30,  'continent' => 'Asia',    'risk_level' => 'low',    'is_popular' => false, 'avg_flight_cost_usd' => 350, 'avg_hotel_per_night_usd' => 80],
            ['country_code' => 'KW', 'name' => 'Кувейт',       'name_uz' => 'Quvayt',         'flag_emoji' => '🇰🇼', 'visa_regime' => 'evisa', 'evisa_available' => true, 'evisa_processing_days' => 5,  'evisa_fee_usd' => 10,  'continent' => 'Asia',    'risk_level' => 'low',    'is_popular' => false, 'avg_flight_cost_usd' => 350, 'avg_hotel_per_night_usd' => 70],
            ['country_code' => 'KE', 'name' => 'Кения',         'name_uz' => 'Keniya',         'flag_emoji' => '🇰🇪', 'visa_regime' => 'evisa', 'evisa_available' => true, 'evisa_processing_days' => 3,  'evisa_fee_usd' => 51,  'continent' => 'Africa',  'risk_level' => 'low',    'is_popular' => false, 'evisa_url' => 'https://www.etakenya.go.ke', 'avg_flight_cost_usd' => 600, 'avg_hotel_per_night_usd' => 40],
            ['country_code' => 'TZ', 'name' => 'Танзания',      'name_uz' => 'Tanzaniya',      'flag_emoji' => '🇹🇿', 'visa_regime' => 'evisa', 'evisa_available' => true, 'evisa_processing_days' => 5,  'evisa_fee_usd' => 50,  'continent' => 'Africa',  'risk_level' => 'low',    'is_popular' => false, 'avg_flight_cost_usd' => 650, 'avg_hotel_per_night_usd' => 40],
            ['country_code' => 'ET', 'name' => 'Эфиопия',       'name_uz' => 'Efiopiya',       'flag_emoji' => '🇪🇹', 'visa_regime' => 'evisa', 'evisa_available' => true, 'evisa_processing_days' => 3,  'evisa_fee_usd' => 52,  'continent' => 'Africa',  'risk_level' => 'low',    'is_popular' => false, 'evisa_url' => 'https://www.evisa.gov.et', 'avg_flight_cost_usd' => 600, 'avg_hotel_per_night_usd' => 30],
            ['country_code' => 'ZW', 'name' => 'Зимбабве',      'name_uz' => 'Zimbabve',       'flag_emoji' => '🇿🇼', 'visa_regime' => 'evisa', 'evisa_available' => true, 'evisa_processing_days' => 5,  'evisa_fee_usd' => 30,  'continent' => 'Africa',  'risk_level' => 'low',    'is_popular' => false, 'avg_flight_cost_usd' => 800, 'avg_hotel_per_night_usd' => 35],
            ['country_code' => 'ZM', 'name' => 'Замбия',        'name_uz' => 'Zambiya',        'flag_emoji' => '🇿🇲', 'visa_regime' => 'evisa', 'evisa_available' => true, 'evisa_processing_days' => 5,  'evisa_fee_usd' => 50,  'continent' => 'Africa',  'risk_level' => 'low',    'is_popular' => false, 'avg_flight_cost_usd' => 800, 'avg_hotel_per_night_usd' => 35],
            ['country_code' => 'CI', 'name' => "Кот-д'Ивуар",   'name_uz' => "Kot-d'Ivuar",    'flag_emoji' => '🇨🇮', 'visa_regime' => 'evisa', 'evisa_available' => true, 'evisa_processing_days' => 5,  'evisa_fee_usd' => 73,  'continent' => 'Africa',  'risk_level' => 'low',    'is_popular' => false, 'avg_flight_cost_usd' => 800, 'avg_hotel_per_night_usd' => 40],
            ['country_code' => 'SN', 'name' => 'Сенегал',       'name_uz' => 'Senegal',        'flag_emoji' => '🇸🇳', 'visa_regime' => 'evisa', 'evisa_available' => true, 'evisa_processing_days' => 5,  'evisa_fee_usd' => 50,  'continent' => 'Africa',  'risk_level' => 'low',    'is_popular' => false, 'avg_flight_cost_usd' => 800, 'avg_hotel_per_night_usd' => 35],
            ['country_code' => 'BJ', 'name' => 'Бенин',         'name_uz' => 'Benin',          'flag_emoji' => '🇧🇯', 'visa_regime' => 'evisa', 'evisa_available' => true, 'evisa_processing_days' => 5,  'evisa_fee_usd' => 50,  'continent' => 'Africa',  'risk_level' => 'low',    'is_popular' => false, 'avg_flight_cost_usd' => 800, 'avg_hotel_per_night_usd' => 30],
            ['country_code' => 'GA', 'name' => 'Габон',         'name_uz' => 'Gabon',          'flag_emoji' => '🇬🇦', 'visa_regime' => 'evisa', 'evisa_available' => true, 'evisa_processing_days' => 5,  'evisa_fee_usd' => 60,  'continent' => 'Africa',  'risk_level' => 'low',    'is_popular' => false, 'avg_flight_cost_usd' => 800, 'avg_hotel_per_night_usd' => 50],
            ['country_code' => 'GN', 'name' => 'Гвинея',        'name_uz' => 'Gvineya',        'flag_emoji' => '🇬🇳', 'visa_regime' => 'evisa', 'evisa_available' => true, 'evisa_processing_days' => 7,  'evisa_fee_usd' => 80,  'continent' => 'Africa',  'risk_level' => 'low',    'is_popular' => false, 'avg_flight_cost_usd' => 800, 'avg_hotel_per_night_usd' => 30],
            ['country_code' => 'LS', 'name' => 'Лесото',        'name_uz' => 'Lesoto',         'flag_emoji' => '🇱🇸', 'visa_regime' => 'evisa', 'evisa_available' => true, 'evisa_processing_days' => 5,  'evisa_fee_usd' => 35,  'continent' => 'Africa',  'risk_level' => 'low',    'is_popular' => false, 'avg_flight_cost_usd' => 900, 'avg_hotel_per_night_usd' => 25],
            ['country_code' => 'SA', 'name' => 'Саудовская Аравия', 'name_uz' => 'Saudiya Arabistoni', 'flag_emoji' => '🇸🇦', 'visa_regime' => 'evisa', 'evisa_available' => true, 'evisa_processing_days' => 3, 'evisa_fee_usd' => 118, 'continent' => 'Asia', 'risk_level' => 'low', 'is_popular' => true, 'avg_flight_cost_usd' => 350, 'avg_hotel_per_night_usd' => 70],
            ['country_code' => 'PH', 'name' => 'Филиппины',     'name_uz' => 'Filippin',       'flag_emoji' => '🇵🇭', 'visa_regime' => 'evisa', 'evisa_available' => true, 'evisa_processing_days' => 5,  'evisa_fee_usd' => 25,  'continent' => 'Asia',    'risk_level' => 'low',    'is_popular' => false, 'avg_flight_cost_usd' => 550, 'avg_hotel_per_night_usd' => 25],
            ['country_code' => 'EG', 'name' => 'Египет',        'name_uz' => 'Misr',           'flag_emoji' => '🇪🇬', 'visa_regime' => 'evisa', 'evisa_available' => true, 'evisa_processing_days' => 5,  'evisa_fee_usd' => 25,  'continent' => 'Africa',  'risk_level' => 'low',    'is_popular' => true,  'avg_flight_cost_usd' => 400, 'avg_hotel_per_night_usd' => 30],
            ['country_code' => 'PK', 'name' => 'Пакистан',      'name_uz' => 'Pokiston',       'flag_emoji' => '🇵🇰', 'visa_regime' => 'evisa', 'evisa_available' => true, 'evisa_processing_days' => 7,  'evisa_fee_usd' => 10,  'continent' => 'Asia',    'risk_level' => 'medium', 'is_popular' => false, 'avg_flight_cost_usd' => 300, 'avg_hotel_per_night_usd' => 25],
        ];
    }

    // =========================================================================
    // Visa required — все страны Шенгена, UK, US, CA, JP, CN и остальные
    // =========================================================================
    private function visaRequiredCountries(): array
    {
        return [
            // Шенгенская зона
            ['country_code' => 'DE', 'name' => 'Германия',        'name_uz' => 'Germaniya',        'flag_emoji' => '🇩🇪', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 80,  'continent' => 'Europe', 'risk_level' => 'medium', 'is_popular' => true,  'insurance_required' => true, 'bank_statement_required' => true, 'hotel_booking_required' => true, 'return_ticket_required' => true, 'avg_flight_cost_usd' => 400, 'avg_hotel_per_night_usd' => 80],
            ['country_code' => 'FR', 'name' => 'Франция',         'name_uz' => 'Frantsiya',        'flag_emoji' => '🇫🇷', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 80,  'continent' => 'Europe', 'risk_level' => 'medium', 'is_popular' => true,  'insurance_required' => true, 'bank_statement_required' => true, 'hotel_booking_required' => true, 'return_ticket_required' => true, 'avg_flight_cost_usd' => 450, 'avg_hotel_per_night_usd' => 90],
            ['country_code' => 'IT', 'name' => 'Италия',          'name_uz' => 'Italiya',          'flag_emoji' => '🇮🇹', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 80,  'continent' => 'Europe', 'risk_level' => 'medium', 'is_popular' => true,  'insurance_required' => true, 'bank_statement_required' => true, 'hotel_booking_required' => true, 'return_ticket_required' => true, 'avg_flight_cost_usd' => 420, 'avg_hotel_per_night_usd' => 80],
            ['country_code' => 'ES', 'name' => 'Испания',         'name_uz' => 'Ispaniya',         'flag_emoji' => '🇪🇸', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 80,  'continent' => 'Europe', 'risk_level' => 'medium', 'is_popular' => true,  'insurance_required' => true, 'bank_statement_required' => true, 'hotel_booking_required' => true, 'return_ticket_required' => true, 'avg_flight_cost_usd' => 450, 'avg_hotel_per_night_usd' => 70],
            ['country_code' => 'NL', 'name' => 'Нидерланды',      'name_uz' => 'Niderlandiya',     'flag_emoji' => '🇳🇱', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 80,  'continent' => 'Europe', 'risk_level' => 'medium', 'is_popular' => false, 'insurance_required' => true, 'bank_statement_required' => true, 'hotel_booking_required' => true, 'return_ticket_required' => true, 'avg_flight_cost_usd' => 450, 'avg_hotel_per_night_usd' => 100],
            ['country_code' => 'BE', 'name' => 'Бельгия',         'name_uz' => 'Belgiya',          'flag_emoji' => '🇧🇪', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 80,  'continent' => 'Europe', 'risk_level' => 'medium', 'is_popular' => false, 'insurance_required' => true, 'bank_statement_required' => true, 'hotel_booking_required' => true, 'return_ticket_required' => true, 'avg_flight_cost_usd' => 460, 'avg_hotel_per_night_usd' => 90],
            ['country_code' => 'AT', 'name' => 'Австрия',         'name_uz' => 'Avstriya',         'flag_emoji' => '🇦🇹', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 80,  'continent' => 'Europe', 'risk_level' => 'medium', 'is_popular' => false, 'insurance_required' => true, 'bank_statement_required' => true, 'hotel_booking_required' => true, 'return_ticket_required' => true, 'avg_flight_cost_usd' => 430, 'avg_hotel_per_night_usd' => 80],
            ['country_code' => 'CH', 'name' => 'Швейцария',       'name_uz' => 'Shveytsariya',     'flag_emoji' => '🇨🇭', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 80,  'continent' => 'Europe', 'risk_level' => 'high',   'is_popular' => false, 'insurance_required' => true, 'bank_statement_required' => true, 'hotel_booking_required' => true, 'return_ticket_required' => true, 'avg_flight_cost_usd' => 500, 'avg_hotel_per_night_usd' => 150],
            ['country_code' => 'SE', 'name' => 'Швеция',          'name_uz' => 'Shvetsiya',        'flag_emoji' => '🇸🇪', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 80,  'continent' => 'Europe', 'risk_level' => 'medium', 'is_popular' => false, 'insurance_required' => true, 'bank_statement_required' => true, 'avg_flight_cost_usd' => 500, 'avg_hotel_per_night_usd' => 100],
            ['country_code' => 'NO', 'name' => 'Норвегия',        'name_uz' => 'Norvegiya',        'flag_emoji' => '🇳🇴', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 80,  'continent' => 'Europe', 'risk_level' => 'medium', 'is_popular' => false, 'insurance_required' => true, 'bank_statement_required' => true, 'avg_flight_cost_usd' => 550, 'avg_hotel_per_night_usd' => 120],
            ['country_code' => 'DK', 'name' => 'Дания',           'name_uz' => 'Daniya',           'flag_emoji' => '🇩🇰', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 80,  'continent' => 'Europe', 'risk_level' => 'medium', 'is_popular' => false, 'insurance_required' => true, 'bank_statement_required' => true, 'avg_flight_cost_usd' => 500, 'avg_hotel_per_night_usd' => 110],
            ['country_code' => 'FI', 'name' => 'Финляндия',       'name_uz' => 'Finlandiya',       'flag_emoji' => '🇫🇮', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 80,  'continent' => 'Europe', 'risk_level' => 'medium', 'is_popular' => false, 'insurance_required' => true, 'bank_statement_required' => true, 'avg_flight_cost_usd' => 500, 'avg_hotel_per_night_usd' => 100],
            ['country_code' => 'PT', 'name' => 'Португалия',      'name_uz' => 'Portugaliya',      'flag_emoji' => '🇵🇹', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 80,  'continent' => 'Europe', 'risk_level' => 'medium', 'is_popular' => false, 'insurance_required' => true, 'bank_statement_required' => true, 'hotel_booking_required' => true, 'return_ticket_required' => true, 'avg_flight_cost_usd' => 500, 'avg_hotel_per_night_usd' => 60],
            ['country_code' => 'GR', 'name' => 'Греция',          'name_uz' => 'Gretsiya',         'flag_emoji' => '🇬🇷', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 80,  'continent' => 'Europe', 'risk_level' => 'medium', 'is_popular' => true,  'insurance_required' => true, 'bank_statement_required' => true, 'hotel_booking_required' => true, 'return_ticket_required' => true, 'avg_flight_cost_usd' => 400, 'avg_hotel_per_night_usd' => 60],
            ['country_code' => 'PL', 'name' => 'Польша',          'name_uz' => 'Polsha',           'flag_emoji' => '🇵🇱', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 80,  'continent' => 'Europe', 'risk_level' => 'medium', 'is_popular' => true,  'insurance_required' => true, 'bank_statement_required' => true, 'hotel_booking_required' => true, 'return_ticket_required' => true, 'avg_flight_cost_usd' => 350, 'avg_hotel_per_night_usd' => 50],
            ['country_code' => 'CZ', 'name' => 'Чехия',           'name_uz' => 'Chexiya',          'flag_emoji' => '🇨🇿', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 80,  'continent' => 'Europe', 'risk_level' => 'medium', 'is_popular' => true,  'insurance_required' => true, 'bank_statement_required' => true, 'hotel_booking_required' => true, 'return_ticket_required' => true, 'avg_flight_cost_usd' => 380, 'avg_hotel_per_night_usd' => 50],
            ['country_code' => 'HU', 'name' => 'Венгрия',         'name_uz' => 'Vengriya',         'flag_emoji' => '🇭🇺', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 80,  'continent' => 'Europe', 'risk_level' => 'medium', 'is_popular' => false, 'insurance_required' => true, 'bank_statement_required' => true, 'hotel_booking_required' => true, 'return_ticket_required' => true, 'avg_flight_cost_usd' => 370, 'avg_hotel_per_night_usd' => 50],
            ['country_code' => 'SK', 'name' => 'Словакия',        'name_uz' => 'Slovakiya',        'flag_emoji' => '🇸🇰', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 80,  'continent' => 'Europe', 'risk_level' => 'medium', 'is_popular' => false, 'insurance_required' => true, 'bank_statement_required' => true, 'avg_flight_cost_usd' => 380, 'avg_hotel_per_night_usd' => 45],
            ['country_code' => 'SI', 'name' => 'Словения',        'name_uz' => 'Sloveniya',        'flag_emoji' => '🇸🇮', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 80,  'continent' => 'Europe', 'risk_level' => 'medium', 'is_popular' => false, 'insurance_required' => true, 'bank_statement_required' => true, 'avg_flight_cost_usd' => 400, 'avg_hotel_per_night_usd' => 55],
            ['country_code' => 'HR', 'name' => 'Хорватия',        'name_uz' => 'Xorvatiya',        'flag_emoji' => '🇭🇷', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 80,  'continent' => 'Europe', 'risk_level' => 'medium', 'is_popular' => false, 'insurance_required' => true, 'bank_statement_required' => true, 'avg_flight_cost_usd' => 400, 'avg_hotel_per_night_usd' => 55],
            ['country_code' => 'BG', 'name' => 'Болгария',        'name_uz' => 'Bolgariya',        'flag_emoji' => '🇧🇬', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 80,  'continent' => 'Europe', 'risk_level' => 'medium', 'is_popular' => false, 'insurance_required' => true, 'bank_statement_required' => true, 'avg_flight_cost_usd' => 350, 'avg_hotel_per_night_usd' => 35],
            ['country_code' => 'RO', 'name' => 'Румыния',         'name_uz' => 'Ruminiya',         'flag_emoji' => '🇷🇴', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 80,  'continent' => 'Europe', 'risk_level' => 'medium', 'is_popular' => false, 'insurance_required' => true, 'bank_statement_required' => true, 'avg_flight_cost_usd' => 350, 'avg_hotel_per_night_usd' => 35],
            ['country_code' => 'LT', 'name' => 'Литва',           'name_uz' => 'Litva',            'flag_emoji' => '🇱🇹', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 80,  'continent' => 'Europe', 'risk_level' => 'medium', 'is_popular' => false, 'insurance_required' => true, 'bank_statement_required' => true, 'avg_flight_cost_usd' => 400, 'avg_hotel_per_night_usd' => 45],
            ['country_code' => 'LV', 'name' => 'Латвия',          'name_uz' => 'Latviya',          'flag_emoji' => '🇱🇻', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 80,  'continent' => 'Europe', 'risk_level' => 'medium', 'is_popular' => false, 'insurance_required' => true, 'bank_statement_required' => true, 'avg_flight_cost_usd' => 400, 'avg_hotel_per_night_usd' => 45],
            ['country_code' => 'EE', 'name' => 'Эстония',         'name_uz' => 'Estoniya',         'flag_emoji' => '🇪🇪', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 80,  'continent' => 'Europe', 'risk_level' => 'medium', 'is_popular' => false, 'insurance_required' => true, 'bank_statement_required' => true, 'avg_flight_cost_usd' => 420, 'avg_hotel_per_night_usd' => 50],
            ['country_code' => 'MT', 'name' => 'Мальта',          'name_uz' => 'Malta',            'flag_emoji' => '🇲🇹', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 80,  'continent' => 'Europe', 'risk_level' => 'medium', 'is_popular' => false, 'insurance_required' => true, 'bank_statement_required' => true, 'avg_flight_cost_usd' => 500, 'avg_hotel_per_night_usd' => 80],
            ['country_code' => 'CY', 'name' => 'Кипр',            'name_uz' => 'Kipr',             'flag_emoji' => '🇨🇾', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 80,  'continent' => 'Europe', 'risk_level' => 'medium', 'is_popular' => false, 'insurance_required' => true, 'bank_statement_required' => true, 'avg_flight_cost_usd' => 400, 'avg_hotel_per_night_usd' => 60],
            ['country_code' => 'LU', 'name' => 'Люксембург',      'name_uz' => 'Lyuksemburg',      'flag_emoji' => '🇱🇺', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 80,  'continent' => 'Europe', 'risk_level' => 'medium', 'is_popular' => false, 'insurance_required' => true, 'bank_statement_required' => true, 'avg_flight_cost_usd' => 500, 'avg_hotel_per_night_usd' => 120],
            ['country_code' => 'IS', 'name' => 'Исландия',        'name_uz' => 'Islandiya',        'flag_emoji' => '🇮🇸', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 80,  'continent' => 'Europe', 'risk_level' => 'medium', 'is_popular' => false, 'insurance_required' => true, 'bank_statement_required' => true, 'avg_flight_cost_usd' => 600, 'avg_hotel_per_night_usd' => 130],
            ['country_code' => 'LI', 'name' => 'Лихтенштейн',    'name_uz' => 'Lixtenshteyn',     'flag_emoji' => '🇱🇮', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 80,  'continent' => 'Europe', 'risk_level' => 'medium', 'is_popular' => false, 'insurance_required' => true, 'bank_statement_required' => true, 'avg_flight_cost_usd' => 500, 'avg_hotel_per_night_usd' => 130],
            ['country_code' => 'IE', 'name' => 'Ирландия',        'name_uz' => 'Irlandiya',        'flag_emoji' => '🇮🇪', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 60,  'continent' => 'Europe', 'risk_level' => 'medium', 'is_popular' => false, 'insurance_required' => true, 'bank_statement_required' => true, 'avg_flight_cost_usd' => 500, 'avg_hotel_per_night_usd' => 90],

            // Non-Schengen Europe
            ['country_code' => 'GB', 'name' => 'Великобритания',  'name_uz' => 'Buyuk Britaniya',  'flag_emoji' => '🇬🇧', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 115, 'continent' => 'Europe', 'risk_level' => 'high',   'is_popular' => true,  'insurance_required' => true, 'bank_statement_required' => true, 'hotel_booking_required' => true, 'return_ticket_required' => true, 'avg_flight_cost_usd' => 500, 'avg_hotel_per_night_usd' => 100, 'is_high_refusal' => true],

            // Северная Америка
            ['country_code' => 'US', 'name' => 'США',             'name_uz' => 'AQSh',             'flag_emoji' => '🇺🇸', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 185, 'continent' => 'North America', 'risk_level' => 'high',   'is_popular' => true,  'bank_statement_required' => true, 'invitation_required' => false, 'avg_flight_cost_usd' => 800, 'avg_hotel_per_night_usd' => 120, 'is_high_refusal' => true],
            ['country_code' => 'CA', 'name' => 'Канада',          'name_uz' => 'Kanada',           'flag_emoji' => '🇨🇦', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 100, 'continent' => 'North America', 'risk_level' => 'high',   'is_popular' => true,  'bank_statement_required' => true, 'insurance_required' => true, 'avg_flight_cost_usd' => 900, 'avg_hotel_per_night_usd' => 100, 'is_high_refusal' => true],
            ['country_code' => 'MX', 'name' => 'Мексика',         'name_uz' => 'Meksika',          'flag_emoji' => '🇲🇽', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 50,  'continent' => 'North America', 'risk_level' => 'medium', 'is_popular' => false, 'avg_flight_cost_usd' => 900, 'avg_hotel_per_night_usd' => 50],

            // Восточная Азия
            ['country_code' => 'JP', 'name' => 'Япония',          'name_uz' => 'Yaponiya',         'flag_emoji' => '🇯🇵', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 30,  'continent' => 'Asia', 'risk_level' => 'high',   'is_popular' => true,  'bank_statement_required' => true, 'hotel_booking_required' => true, 'return_ticket_required' => true, 'insurance_required' => true, 'avg_flight_cost_usd' => 600, 'avg_hotel_per_night_usd' => 80],
            ['country_code' => 'CN', 'name' => 'Китай',           'name_uz' => 'Xitoy',            'flag_emoji' => '🇨🇳', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 140, 'continent' => 'Asia', 'risk_level' => 'medium', 'is_popular' => true,  'bank_statement_required' => true, 'invitation_required' => true, 'avg_flight_cost_usd' => 400, 'avg_hotel_per_night_usd' => 40],
            ['country_code' => 'TW', 'name' => 'Тайвань',         'name_uz' => 'Tayvan',           'flag_emoji' => '🇹🇼', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 66,  'continent' => 'Asia', 'risk_level' => 'medium', 'is_popular' => false, 'avg_flight_cost_usd' => 600, 'avg_hotel_per_night_usd' => 50],
            ['country_code' => 'HK', 'name' => 'Гонконг',         'name_uz' => 'Gonkong',          'flag_emoji' => '🇭🇰', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 30,  'continent' => 'Asia', 'risk_level' => 'medium', 'is_popular' => false, 'avg_flight_cost_usd' => 550, 'avg_hotel_per_night_usd' => 80],

            // Южная Америка
            ['country_code' => 'BR', 'name' => 'Бразилия',        'name_uz' => 'Braziliya',        'flag_emoji' => '🇧🇷', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 80,  'continent' => 'South America', 'risk_level' => 'medium', 'is_popular' => false, 'avg_flight_cost_usd' => 1000, 'avg_hotel_per_night_usd' => 40],
            ['country_code' => 'AR', 'name' => 'Аргентина',       'name_uz' => 'Argentina',        'flag_emoji' => '🇦🇷', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 150, 'continent' => 'South America', 'risk_level' => 'medium', 'is_popular' => false, 'avg_flight_cost_usd' => 1100, 'avg_hotel_per_night_usd' => 35],
            ['country_code' => 'CL', 'name' => 'Чили',            'name_uz' => 'Chili',            'flag_emoji' => '🇨🇱', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 60,  'continent' => 'South America', 'risk_level' => 'medium', 'is_popular' => false, 'avg_flight_cost_usd' => 1100, 'avg_hotel_per_night_usd' => 40],
            ['country_code' => 'CO', 'name' => 'Колумбия',        'name_uz' => 'Kolumbiya',        'flag_emoji' => '🇨🇴', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 52,  'continent' => 'South America', 'risk_level' => 'medium', 'is_popular' => false, 'avg_flight_cost_usd' => 1000, 'avg_hotel_per_night_usd' => 30],
            ['country_code' => 'PE', 'name' => 'Перу',            'name_uz' => 'Peru',             'flag_emoji' => '🇵🇪', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 30,  'continent' => 'South America', 'risk_level' => 'medium', 'is_popular' => false, 'avg_flight_cost_usd' => 1100, 'avg_hotel_per_night_usd' => 30],
            ['country_code' => 'VE', 'name' => 'Венесуэла',       'name_uz' => 'Venesuela',        'flag_emoji' => '🇻🇪', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 30,  'continent' => 'South America', 'risk_level' => 'high',   'is_popular' => false, 'avg_flight_cost_usd' => 1100, 'avg_hotel_per_night_usd' => 30],
            ['country_code' => 'UY', 'name' => 'Уругвай',         'name_uz' => 'Urugvay',          'flag_emoji' => '🇺🇾', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 42,  'continent' => 'South America', 'risk_level' => 'low',    'is_popular' => false, 'avg_flight_cost_usd' => 1200, 'avg_hotel_per_night_usd' => 40],
            ['country_code' => 'BO', 'name' => 'Боливия',         'name_uz' => 'Boliviya',         'flag_emoji' => '🇧🇴', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 30,  'continent' => 'South America', 'risk_level' => 'low',    'is_popular' => false, 'avg_flight_cost_usd' => 1100, 'avg_hotel_per_night_usd' => 25],
            ['country_code' => 'PY', 'name' => 'Парагвай',        'name_uz' => 'Paragvay',         'flag_emoji' => '🇵🇾', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 30,  'continent' => 'South America', 'risk_level' => 'low',    'is_popular' => false, 'avg_flight_cost_usd' => 1200, 'avg_hotel_per_night_usd' => 25],
            ['country_code' => 'GY', 'name' => 'Гайана',          'name_uz' => 'Gayana',           'flag_emoji' => '🇬🇾', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 40,  'continent' => 'South America', 'risk_level' => 'low',    'is_popular' => false, 'avg_flight_cost_usd' => 1200, 'avg_hotel_per_night_usd' => 30],
            ['country_code' => 'SR', 'name' => 'Суринам',         'name_uz' => 'Surinam',          'flag_emoji' => '🇸🇷', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 45,  'continent' => 'South America', 'risk_level' => 'low',    'is_popular' => false, 'avg_flight_cost_usd' => 1300, 'avg_hotel_per_night_usd' => 35],

            // Африка (visa required)
            ['country_code' => 'ZA', 'name' => 'ЮАР',             'name_uz' => 'JAR',              'flag_emoji' => '🇿🇦', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 60,  'continent' => 'Africa', 'risk_level' => 'medium', 'is_popular' => false, 'avg_flight_cost_usd' => 700, 'avg_hotel_per_night_usd' => 50],
            ['country_code' => 'NG', 'name' => 'Нигерия',         'name_uz' => 'Nigeriya',         'flag_emoji' => '🇳🇬', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 80,  'continent' => 'Africa', 'risk_level' => 'medium', 'is_popular' => false, 'avg_flight_cost_usd' => 700, 'avg_hotel_per_night_usd' => 40],
            ['country_code' => 'GH', 'name' => 'Гана',            'name_uz' => 'Gana',             'flag_emoji' => '🇬🇭', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 60,  'continent' => 'Africa', 'risk_level' => 'low',    'is_popular' => false, 'avg_flight_cost_usd' => 750, 'avg_hotel_per_night_usd' => 35],
            ['country_code' => 'CM', 'name' => 'Камерун',         'name_uz' => 'Kamerun',          'flag_emoji' => '🇨🇲', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 90,  'continent' => 'Africa', 'risk_level' => 'low',    'is_popular' => false, 'avg_flight_cost_usd' => 800, 'avg_hotel_per_night_usd' => 35],
            ['country_code' => 'DZ', 'name' => 'Алжир',           'name_uz' => 'Jazoir',           'flag_emoji' => '🇩🇿', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 60,  'continent' => 'Africa', 'risk_level' => 'medium', 'is_popular' => false, 'avg_flight_cost_usd' => 500, 'avg_hotel_per_night_usd' => 40],
            ['country_code' => 'MA', 'name' => 'Марокко',         'name_uz' => 'Marokash',         'flag_emoji' => '🇲🇦', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 25,  'continent' => 'Africa', 'risk_level' => 'low',    'is_popular' => false, 'avg_flight_cost_usd' => 500, 'avg_hotel_per_night_usd' => 35],
            ['country_code' => 'TN', 'name' => 'Тунис',           'name_uz' => 'Tunis',            'flag_emoji' => '🇹🇳', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 30,  'continent' => 'Africa', 'risk_level' => 'low',    'is_popular' => false, 'avg_flight_cost_usd' => 450, 'avg_hotel_per_night_usd' => 30],
            ['country_code' => 'LY', 'name' => 'Ливия',           'name_uz' => 'Liviya',           'flag_emoji' => '🇱🇾', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 50,  'continent' => 'Africa', 'risk_level' => 'high',   'is_popular' => false, 'avg_flight_cost_usd' => 500, 'avg_hotel_per_night_usd' => 40],
            ['country_code' => 'SD', 'name' => 'Судан',           'name_uz' => 'Sudan',            'flag_emoji' => '🇸🇩', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 50,  'continent' => 'Africa', 'risk_level' => 'high',   'is_popular' => false, 'avg_flight_cost_usd' => 600, 'avg_hotel_per_night_usd' => 30],
            ['country_code' => 'AO', 'name' => 'Ангола',          'name_uz' => 'Angola',           'flag_emoji' => '🇦🇴', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 120, 'continent' => 'Africa', 'risk_level' => 'medium', 'is_popular' => false, 'avg_flight_cost_usd' => 800, 'avg_hotel_per_night_usd' => 50],
            ['country_code' => 'CD', 'name' => 'ДР Конго',        'name_uz' => 'Kongo DR',         'flag_emoji' => '🇨🇩', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 100, 'continent' => 'Africa', 'risk_level' => 'high',   'is_popular' => false, 'avg_flight_cost_usd' => 800, 'avg_hotel_per_night_usd' => 40],
            ['country_code' => 'CG', 'name' => 'Конго',           'name_uz' => 'Kongo',            'flag_emoji' => '🇨🇬', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 80,  'continent' => 'Africa', 'risk_level' => 'medium', 'is_popular' => false, 'avg_flight_cost_usd' => 800, 'avg_hotel_per_night_usd' => 40],
            ['country_code' => 'ER', 'name' => 'Эритрея',         'name_uz' => 'Eritreya',         'flag_emoji' => '🇪🇷', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 70,  'continent' => 'Africa', 'risk_level' => 'high',   'is_popular' => false, 'avg_flight_cost_usd' => 700, 'avg_hotel_per_night_usd' => 25],
            ['country_code' => 'ML', 'name' => 'Мали',            'name_uz' => 'Mali',             'flag_emoji' => '🇲🇱', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 60,  'continent' => 'Africa', 'risk_level' => 'high',   'is_popular' => false, 'avg_flight_cost_usd' => 800, 'avg_hotel_per_night_usd' => 25],
            ['country_code' => 'NE', 'name' => 'Нигер',           'name_uz' => 'Niger',            'flag_emoji' => '🇳🇪', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 40,  'continent' => 'Africa', 'risk_level' => 'high',   'is_popular' => false, 'avg_flight_cost_usd' => 800, 'avg_hotel_per_night_usd' => 25],
            ['country_code' => 'TD', 'name' => 'Чад',             'name_uz' => 'Chad',             'flag_emoji' => '🇹🇩', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 100, 'continent' => 'Africa', 'risk_level' => 'high',   'is_popular' => false, 'avg_flight_cost_usd' => 800, 'avg_hotel_per_night_usd' => 30],
            ['country_code' => 'BF', 'name' => 'Буркина-Фасо',   'name_uz' => 'Burkina-Faso',     'flag_emoji' => '🇧🇫', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 50,  'continent' => 'Africa', 'risk_level' => 'medium', 'is_popular' => false, 'avg_flight_cost_usd' => 800, 'avg_hotel_per_night_usd' => 25],
            ['country_code' => 'SL', 'name' => 'Сьерра-Леоне',   'name_uz' => 'Syerra-Leone',     'flag_emoji' => '🇸🇱', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 80,  'continent' => 'Africa', 'risk_level' => 'medium', 'is_popular' => false, 'avg_flight_cost_usd' => 800, 'avg_hotel_per_night_usd' => 30],
            ['country_code' => 'LR', 'name' => 'Либерия',         'name_uz' => 'Liberiya',         'flag_emoji' => '🇱🇷', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 70,  'continent' => 'Africa', 'risk_level' => 'medium', 'is_popular' => false, 'avg_flight_cost_usd' => 900, 'avg_hotel_per_night_usd' => 30],
            ['country_code' => 'GM', 'name' => 'Гамбия',          'name_uz' => 'Gambiya',          'flag_emoji' => '🇬🇲', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 40,  'continent' => 'Africa', 'risk_level' => 'low',    'is_popular' => false, 'avg_flight_cost_usd' => 800, 'avg_hotel_per_night_usd' => 25],
            ['country_code' => 'GW', 'name' => 'Гвинея-Бисау',   'name_uz' => 'Gvineya-Bisau',    'flag_emoji' => '🇬🇼', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 60,  'continent' => 'Africa', 'risk_level' => 'medium', 'is_popular' => false, 'avg_flight_cost_usd' => 900, 'avg_hotel_per_night_usd' => 25],
            ['country_code' => 'SS', 'name' => 'Южный Судан',     'name_uz' => 'Janubiy Sudan',    'flag_emoji' => '🇸🇸', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 50,  'continent' => 'Africa', 'risk_level' => 'high',   'is_popular' => false, 'avg_flight_cost_usd' => 700, 'avg_hotel_per_night_usd' => 30],
            ['country_code' => 'CF', 'name' => 'ЦАР',             'name_uz' => 'MAR',              'flag_emoji' => '🇨🇫', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 60,  'continent' => 'Africa', 'risk_level' => 'high',   'is_popular' => false, 'avg_flight_cost_usd' => 900, 'avg_hotel_per_night_usd' => 30],
            ['country_code' => 'BI', 'name' => 'Бурунди',         'name_uz' => 'Burundi',          'flag_emoji' => '🇧🇮', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 40,  'continent' => 'Africa', 'risk_level' => 'medium', 'is_popular' => false, 'avg_flight_cost_usd' => 800, 'avg_hotel_per_night_usd' => 25],
            ['country_code' => 'BW', 'name' => 'Ботсвана',        'name_uz' => 'Botsvana',         'flag_emoji' => '🇧🇼', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 0,   'continent' => 'Africa', 'risk_level' => 'low',    'is_popular' => false, 'avg_flight_cost_usd' => 800, 'avg_hotel_per_night_usd' => 45],
            ['country_code' => 'NA', 'name' => 'Намибия',         'name_uz' => 'Namibiya',         'flag_emoji' => '🇳🇦', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 0,   'continent' => 'Africa', 'risk_level' => 'low',    'is_popular' => false, 'avg_flight_cost_usd' => 800, 'avg_hotel_per_night_usd' => 40],
            ['country_code' => 'SZ', 'name' => 'Эсватини',        'name_uz' => 'Esvatini',         'flag_emoji' => '🇸🇿', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 0,   'continent' => 'Africa', 'risk_level' => 'low',    'is_popular' => false, 'avg_flight_cost_usd' => 800, 'avg_hotel_per_night_usd' => 30],
            ['country_code' => 'MU', 'name' => 'Маврикий',        'name_uz' => 'Mavrikiy',         'flag_emoji' => '🇲🇺', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 0,   'continent' => 'Africa', 'risk_level' => 'low',    'is_popular' => false, 'avg_flight_cost_usd' => 800, 'avg_hotel_per_night_usd' => 70],

            // Ближний Восток (visa required)
            ['country_code' => 'IL', 'name' => 'Израиль',         'name_uz' => 'Isroil',           'flag_emoji' => '🇮🇱', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 0,   'continent' => 'Asia', 'risk_level' => 'high',   'is_popular' => false, 'bank_statement_required' => true, 'avg_flight_cost_usd' => 400, 'avg_hotel_per_night_usd' => 80],
            ['country_code' => 'IQ', 'name' => 'Ирак',            'name_uz' => 'Iroq',             'flag_emoji' => '🇮🇶', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 50,  'continent' => 'Asia', 'risk_level' => 'high',   'is_popular' => false, 'avg_flight_cost_usd' => 350, 'avg_hotel_per_night_usd' => 40],
            ['country_code' => 'SY', 'name' => 'Сирия',           'name_uz' => 'Suriya',           'flag_emoji' => '🇸🇾', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 30,  'continent' => 'Asia', 'risk_level' => 'high',   'is_popular' => false, 'avg_flight_cost_usd' => 400, 'avg_hotel_per_night_usd' => 25],
            ['country_code' => 'YE', 'name' => 'Йемен',           'name_uz' => 'Yaman',            'flag_emoji' => '🇾🇪', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 50,  'continent' => 'Asia', 'risk_level' => 'high',   'is_popular' => false, 'avg_flight_cost_usd' => 500, 'avg_hotel_per_night_usd' => 25],

            // Юго-Восточная Азия (visa required)
            ['country_code' => 'AF', 'name' => 'Афганистан',      'name_uz' => "Afg'oniston",      'flag_emoji' => '🇦🇫', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 60,  'continent' => 'Asia', 'risk_level' => 'high', 'is_popular' => false, 'avg_flight_cost_usd' => 250, 'avg_hotel_per_night_usd' => 20],
            ['country_code' => 'KP', 'name' => 'Северная Корея',  'name_uz' => 'Shimoliy Koreya',  'flag_emoji' => '🇰🇵', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 50,  'continent' => 'Asia', 'risk_level' => 'high', 'is_popular' => false, 'avg_flight_cost_usd' => 800, 'avg_hotel_per_night_usd' => 50],

            // Центральная Америка (visa required)
            ['country_code' => 'GT', 'name' => 'Гватемала',       'name_uz' => 'Gvatemala',        'flag_emoji' => '🇬🇹', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 25,  'continent' => 'North America', 'risk_level' => 'medium', 'is_popular' => false, 'avg_flight_cost_usd' => 1000, 'avg_hotel_per_night_usd' => 30],
            ['country_code' => 'SV', 'name' => 'Сальвадор',       'name_uz' => 'Salvador',         'flag_emoji' => '🇸🇻', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 30,  'continent' => 'North America', 'risk_level' => 'medium', 'is_popular' => false, 'avg_flight_cost_usd' => 1000, 'avg_hotel_per_night_usd' => 25],
            ['country_code' => 'CR', 'name' => 'Коста-Рика',      'name_uz' => 'Kosta-Rika',       'flag_emoji' => '🇨🇷', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 20,  'continent' => 'North America', 'risk_level' => 'low',    'is_popular' => false, 'avg_flight_cost_usd' => 1000, 'avg_hotel_per_night_usd' => 40],
            ['country_code' => 'BZ', 'name' => 'Белиз',           'name_uz' => 'Beliz',            'flag_emoji' => '🇧🇿', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 50,  'continent' => 'North America', 'risk_level' => 'low',    'is_popular' => false, 'avg_flight_cost_usd' => 1100, 'avg_hotel_per_night_usd' => 40],
            ['country_code' => 'CU', 'name' => 'Куба',            'name_uz' => 'Kuba',             'flag_emoji' => '🇨🇺', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 50,  'continent' => 'North America', 'risk_level' => 'medium', 'is_popular' => false, 'avg_flight_cost_usd' => 1000, 'avg_hotel_per_night_usd' => 35],
            ['country_code' => 'JM', 'name' => 'Ямайка',          'name_uz' => 'Yamayka',          'flag_emoji' => '🇯🇲', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 50,  'continent' => 'North America', 'risk_level' => 'low',    'is_popular' => false, 'avg_flight_cost_usd' => 1100, 'avg_hotel_per_night_usd' => 50],
            ['country_code' => 'TT', 'name' => 'Тринидад и Тобаго','name_uz' => 'Trinidad va Tobago','flag_emoji' => '🇹🇹', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 50, 'continent' => 'North America', 'risk_level' => 'low', 'is_popular' => false, 'avg_flight_cost_usd' => 1200, 'avg_hotel_per_night_usd' => 60],

            // Океания (visa required)
            ['country_code' => 'FJ', 'name' => 'Фиджи',           'name_uz' => 'Fiji',             'flag_emoji' => '🇫🇯', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 0,   'continent' => 'Oceania', 'risk_level' => 'low', 'is_popular' => false, 'avg_flight_cost_usd' => 1400, 'avg_hotel_per_night_usd' => 60],
            ['country_code' => 'PG', 'name' => 'Папуа — Новая Гвинея', 'name_uz' => 'Papua — Yangi Gvineya', 'flag_emoji' => '🇵🇬', 'visa_regime' => 'visa_required', 'visa_fee_usd' => 50, 'continent' => 'Oceania', 'risk_level' => 'medium', 'is_popular' => false, 'avg_flight_cost_usd' => 1400, 'avg_hotel_per_night_usd' => 50],
        ];
    }
}
